### ISSUE TITLE
Exporting model to ONNX not working

### ISSUE THREAD

**Issue by kskdermolab** [Lightning-AI/pytorch-lightning#13022]
## 🐛 Bug - Help

I was able to train the model on AVA, save the checkpoint, load it and test it and everything was fine. but I have problems to convert it to ONNX.

I had to register "torchvision::roi_align" operation but the internal arguments seems to be wrong. Here is a part of the code that I used:
```py
import pytorch_lightning
import torchvision as tv
from pytorchvideo.models.hub import slow_r50_detection
from torchvision.ops import roi_align
from torch.onnx import register_custom_op_symbolic
from data_modules import AvaDataModule  # the loader instance the pytorchvideo.data.Ava dataset


register_custom_op_symbolic("torchvision::roi_align", roi_align, 10)


class VideoClassificationLightningModule(pytorch_lightning.LightningModule):
    def __init__(self, model):
        super().__init__()
        self.model = model
        self.output_size = (7, 7)

    def forward(self, x, y):
        return tv.ops.roi_align(input=x, boxes=y, output_size=self.output_size)

model = slow_r50_detection(pretrained=True)
model.eval()
classification_module = VideoClassificationLightningModule(model=model)

data_module = AvaDataModule(
    train_cfg=...,
    val_cfg=...,
    train_transform=...,
    val_transform=...,
    batch_size=...,
    clip_duration=...,
)
dummy_input = next(iter(data_module.train_dataset))["video"]

dummy_boxes = torch.Tensor([
    [0.0, 0.083, 0.136, 0.437, 0.911],
    [0.0, 0.394, 0.052, 0.966, 0.989]]
).float()  # torch.Size([2, 5])

dummy_input = torch.unsqueeze(dummy_input, dim=0)  # torch.Size([1, 3, 4, 256, 256])
classification_module.to_onnx(
        "output_model.onnx",
        (dummy_input, dummy_boxes,),
        export_params=True,
        opset_version=10,
)
```

> I was following this [issue on the pytorch repository](https://github.com/pytorch/pytorch/issues/24817) where had to register the same operation. I don't understand well which has to be the output size. When I execute the `model.eval()` I have the details of the roi_align with the next information `(roi_layer): RoIAlign(output_size=(7, 7), spatial_scale=0.0625, sampling_ratio=0, aligned=False)`. Is because of that that I think the output layer must be (7, 7). But any comment about this will be useful.

The error that I have is the next one:
```sh
Traceback (most recent call last):
  File "main.py", line 237, in export
    classification_module.to_onnx(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/lightning.py", line 1867, in to_onnx
    torch.onnx.export(self, input_sample, file_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 354, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1194, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
TypeError: roi_align() takes from 3 to 6 positional arguments but 8 were given
(Occurred when translating roi_align).
```

The signature of the `roi_align` is this:
```sh
Signature:
roi_align(
    input: torch.Tensor,
    boxes: torch.Tensor,
    output_size: None,
    spatial_scale: float = 1.0,
    sampling_ratio: int = -1,
    aligned: bool = False,
) -> torch.Tensor
```

and the inputs that receive at that point is something like this:
```sh
(x defined in (%x : Float(1, 3, 4, 256, 256, strides=[786432, 262144, 65536, 256, 1], requires_grad=0, device=cpu), %boxes : Float(2, 5, strides=[5, 1], requires_grad=0, device=cpu), %model.model.blocks.0.conv.weight : Float(64, 3, 1, 7, 7, strides=[147, 49, 49, 7, 1], requires_grad=1, device=cpu), %model.model.blocks.0.norm.weight : Float(64, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.0.norm.bias : Float(64, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.0.norm.running_mean : Float(64, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.0.norm.running_var : Float(64, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.0.norm.num_batches_tracked : Long(requires_grad=0, device=cpu), %model.model.blocks.1.res_blocks.0.branch1_conv.weight : Float(256, 64, 1, 1, 1, strides=[64, 1, 1, 1, 1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch1_norm.weight : Float(256, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch1_norm.bias : Float(256, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch1_norm.running_mean : Float(256, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.1.res_blocks.0.branch1_norm.running_var : Float(256, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.1.res_blocks.0.branch1_norm.num_batches_tracked : Long(requires_grad=0, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.conv_a.weight : Float(64, 64, 1, 1, 1, strides=[64, 1, 1, 1, 1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.norm_a.weight : Float(64, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.norm_a.bias : Float(64, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.norm_a.running_mean : Float(64, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.norm_a.running_var : Float(64, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.norm_a.num_batches_tracked : Long(requires_grad=0, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.conv_b.weight : Float(64, 64, 1, 3, 3, strides=[576, 9, 9, 3, 1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.norm_b.weight : Float(64, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.1.res_blocks.0.branch2.norm_b.bias : Float(64, strides=[1], requires_grad=1, device=cpu
...
...
 %model.model.blocks.4.res_blocks.2.branch2.norm_b.running_mean : Float(512, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.norm_b.running_var : Float(512, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.norm_b.num_batches_tracked : Long(requires_grad=0, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.conv_c.weight : Float(2048, 512, 1, 1, 1, strides=[512, 1, 1, 1, 1], requires_grad=1, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.norm_c.weight : Float(2048, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.norm_c.bias : Float(2048, strides=[1], requires_grad=1, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.norm_c.running_mean : Float(2048, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.norm_c.running_var : Float(2048, strides=[1], requires_grad=0, device=cpu), %model.model.blocks.4.res_blocks.2.branch2.norm_c.num_batches_tracked : Long(requires_grad=0, device=cpu), %model.detection_head.proj.weight : Float(80, 2048, strides=[2048, 1], requires_grad=1, device=cpu), %model.detection_head.proj.bias : Float(80, strides=[1], requires_grad=1, device=cpu) = prim::Param()        ), 322 defined in (%322 : Double(device=cpu) = onnx::Constant[value={1}]()                                                                                                                                       ), 323 defined in (%323 : Long(device=cpu) = onnx::Constant[value={7}]()                                                                                                                                         ), 324 defined in (%324 : Long(device=cpu) = onnx::Constant[value={7}]()                                                                                                                                         ), 325 defined in (%325 : Long(device=cpu) = onnx::Constant[value={-1}]()                                                                                                                                        ), 326 defined in (%326 : Bool(device=cpu) = onnx::Constant[value={0}]()                                                                                                                                         ))
```

Any help will be appreciated.

cc @otaj

**Comment by rohitgr7** [comment]
seems like the issue is a 3rd party issue? https://github.com/pytorch/pytorch/issues/24817#issuecomment-854329563
