### ISSUE TITLE
Lightning applications fail when Path(".") is used

### ISSUE THREAD

**Issue by krishnakalyan3** [Lightning-AI/pytorch-lightning#13521]
Using the `Path(".")` object from `lightning.app.storage` leads to the error below. The failure takes about 7 minutes to appear in the lighting logs.

```
[root.random_work] 2022-07-03T11:58:46.469Z botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
[root.random_work] 2022-07-03T11:58:46.469Z The above exception was the direct cause of the following exception:
[root.random_work] 2022-07-03T11:58:46.469Z Traceback (most recent call last):
[root.random_work] 2022-07-03T11:58:46.469Z     sys.exit(main())
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[root.random_work] 2022-07-03T11:58:46.469Z     return self.main(*args, **kwargs)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
[root.random_work] 2022-07-03T11:58:46.469Z     rv = self.invoke(ctx)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.random_work] 2022-07-03T11:58:46.469Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.random_work] 2022-07-03T11:58:46.469Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[root.random_work] 2022-07-03T11:58:46.469Z     return ctx.invoke(self.callback, **ctx.params)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[root.random_work] 2022-07-03T11:58:46.469Z     return __callback(*args, **kwargs)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/cli/__main__.py", line 86, in run_work
[root.random_work] 2022-07-03T11:58:46.469Z     run_lightning_work(
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 49, in wrapper
[root.random_work] 2022-07-03T11:58:46.469Z     res = func(*args, **kwargs)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 73, in wrapper
[root.random_work] 2022-07-03T11:58:46.469Z     res = func(*args, **kwargs)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 109, in run_lightning_work
[root.random_work] 2022-07-03T11:58:46.469Z     WorkRunner(
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 308, in __call__
[root.random_work] 2022-07-03T11:58:46.469Z     raise e
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 291, in __call__
[root.random_work] 2022-07-03T11:58:46.469Z     self.run_once()
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 404, in run_once
[root.random_work] 2022-07-03T11:58:46.469Z     persist_artifacts(work=self.work)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 533, in persist_artifacts
[root.random_work] 2022-07-03T11:58:46.469Z     copy_files(artifact_path, destination_path)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/storage/copier.py", line 125, in copy_files
[root.random_work] 2022-07-03T11:58:46.469Z     raise exception
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/storage/copier.py", line 108, in _copy
[root.random_work] 2022-07-03T11:58:46.469Z     fs.put(str(from_path), str(to_path), recursive=False)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
[root.random_work] 2022-07-03T11:58:46.469Z     return sync(self.loop, func, *args, **kwargs)
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
[root.random_work] 2022-07-03T11:58:46.469Z     raise return_result
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
[root.random_work] 2022-07-03T11:58:46.469Z     result[0] = await coro
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 490, in _put
[root.random_work] 2022-07-03T11:58:46.469Z     return await _run_coros_in_chunks(
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 249, in _run_coros_in_chunks
[root.random_work] 2022-07-03T11:58:46.469Z     await asyncio.gather(*chunk, return_exceptions=return_exceptions),
[root.random_work] 2022-07-03T11:58:46.469Z   File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
[root.random_work] 2022-07-03T11:58:46.469Z     return await fut
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 948, in _put_file
[root.random_work] 2022-07-03T11:58:46.469Z     await self._call_s3(
[root.random_work] 2022-07-03T11:58:46.469Z   File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 281, in _call_s3
[root.random_work] 2022-07-03T11:58:46.469Z     raise err
[root.random_work] 2022-07-03T11:58:46.469Z PermissionError: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by krishnakalyan3** [comment]
Example:
```import lightning as L
from typing import Optional
from lightning.app.storage import Path

class RandomWork(L.LightningWork):
    def __init__(self):
        super().__init__()
        self.storage = None

    def run(self):
        self.storage = Path(".")
        print("Random Work")

class Manager(L.LightningFlow):
    def __init__(self) -> None:
        super().__init__()
        self.random_work = RandomWork()

    def run(self):
        self.random_work.run()

app = L.LightningApp(Manager())```
