### ISSUE TITLE
lightning app lightning run app docs/source-app/examples/github_repo_runner/app.py fails with train_script.py` wasn't found.

### ISSUE THREAD

**Issue by robert-s-lee** [Lightning-AI/pytorch-lightning#13709]
## 📚 Documentation

Creating this as a cut and paste of example is not working.  Not sure whether this is a small cut/paste issue or another issue.

Following https://lightning.ai/lightning-docs/examples/github_repo_runner/github_repo_runner_step_5.html

typed
```
git clone https://github.com/Lightning-AI/lightning
cd lightning
lightning app lightning run app docs/source-app/examples/github_repo_runner/app.py fails with train_script.py` wasn't found.
```
saw
```
(lai) base> lightning run app docs/source-app/examples/github_repo_runner/app.py

Your Lightning App is starting. This won't take long.
2022-07-18 09:28:07.827 INFO    numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-07-18 09:28:07.827 INFO    numexpr.utils: NumExpr defaulting to 8 threads.
2022-07-18 09:28:09.997 INFO    numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-07-18 09:28:09.997 INFO    numexpr.utils: NumExpr defaulting to 8 threads.
INFO: Your app has started. View it in your browser: http://127.0.0.1:7501/view
INFO: Your Lightning App is being stopped. This won't take long.
INFO: Your Lightning App has been stopped successfully!
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lai/bin/lightning", line 33, in <module>
    sys.exit(load_entry_point('lightning==2022.6.15.post2', 'console_scripts', 'lightning')())
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/lightning_app/cli/lightning_cli.py", line 115, in run_app
    _run_app(file, cloud, without_server, no_cache, name, blocking, open_ui, env)
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/lightning_app/cli/lightning_cli.py", line 81, in _run_app
    dispatch(
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/lightning_app/runners/runtime.py", line 63, in dispatch
    return runtime.dispatch(on_before_run=on_before_run, name=name, no_cache=no_cache)
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/lightning_app/runners/multiprocess.py", line 87, in dispatch
    self.app._run()
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/lightning_app/core/app.py", line 392, in _run
    done = self.run_once()
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/lightning_app/core/app.py", line 342, in run_once
    self.root.run()
  File "docs/source-app/examples/github_repo_runner/app.py", line 283, in run
    self.flow.run()
  File "docs/source-app/examples/github_repo_runner/app.py", line 162, in run
    self._handle_request(request_id, deepcopy(request))
  File "docs/source-app/examples/github_repo_runner/app.py", line 172, in _handle_request
    work = work_cls(id=request["id"], **request["train"])
  File "docs/source-app/examples/github_repo_runner/app.py", line 76, in __init__
    super().__init__(*args, **kwargs)
  File "docs/source-app/examples/github_repo_runner/app.py", line 40, in __init__
    super().__init__(
  File "/opt/miniconda3/envs/lai/lib/python3.8/site-packages/lightning_app/components/python/tracer.py", line 77, in __init__
    raise FileNotFoundError(f"The provided `script_path` {script_path}` wasn't found.")
FileNotFoundError: The provided `script_path` train_script.py` wasn't found.
```

**Comment by tchaton** [comment]
Yes, I need to push the fix. Thanks for reminding me ;)
