### ISSUE TITLE
`RichProgressBar` in v1.6 is slower than v1.5

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/pytorch-lightning#13937]
## 🐛 Bug
Similarly to (but independently of) #13179, there's a regression in speed of the rich progress bar between 1.5 and 1.6.

```
time: 2.059369374997914   # v1.5.10
time: 13.186531708983239  # v1.6.0
time: 11.988152374979109  # v1.6.5
time: 12.897805292042904  # master (aefb9ab43f9a8e6704558a346dbae1a00044bb45)
```

### To Reproduce

```python
from time import monotonic
import torch
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import RichProgressBar

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

def main():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = BoringModel()
    trainer = Trainer(
        max_epochs=100,
        enable_model_summary=False,
        enable_checkpointing=False,
        logger=False,
        benchmark=False,  # True by default in 1.6.{0-3}.
        callbacks=RichProgressBar(),
    )
    t0 = monotonic()
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    print("time:", monotonic() - t0)

if __name__ == "__main__":
    main()
```

### Expected behavior
There should be no regression unless there's a reasonable explanation.

### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): n/a
- PyTorch Lightning Version (e.g., 1.5.0): master (aefb9ab43f9a8e6704558a346dbae1a00044bb45), 1.6.5, 1.6.0, 1.5.10
- PyTorch Version (e.g., 1.10): 1.12
- Python version (e.g., 3.9): 3.10
- OS (e.g., Linux): macOS
- CUDA/cuDNN version: n/a
- GPU models and configuration: Apple Silicon M1
- How you installed PyTorch (`conda`, `pip`, source): pip
- If compiling from source, the output of `torch.__config__.show()`:
- Running environment of LightningApp (e.g. local, cloud): n/a
- Any other relevant information: `rich==12.5.1`

### Additional context
Investigating!

https://github.com/Lightning-AI/lightning/pulls?q=is%3Apr+label%3A%22progress+bar%3A+rich%22+milestone%3A%22pl%3A1.6%22+

cc @tchaton @rohitgr7 @kaushikb11 @borda @akihironitta

**Comment by rohitgr7** [comment]
> time: 2.059369374997914   # v1.5.10
time: 13.186531708983239  # v1.6.0
time: 11.988152374979109  # v1.6.5
time: 12.897805292042904  # master (aefb9ab43f9a8e6704558a346dbae1a00044bb45)

it's huge... maybe it's the same `refresh` that is causing the issue

**Comment by shenoynikhil** [comment]
@akihironitta Can I help resolve this issue?

**Comment by akihironitta** [comment]
Hi @shenoynikhil, thank you for showing your interest in this issue! I think I'll soon be concluding this issue with some improvement to the current impl. and report with benchmarks/explanation, so if you're still interested in making contributions, it would be great if you could pick any other existing issues!

**Comment by kaushikb11** [comment]
@akihironitta How does it compare with TQDMProgressBar over recent releases?

**Comment by bhimrazy** [comment]
Is this issue still relevant?

**Comment by bhimrazy** [comment]
A sample benchmark I tested with the new versions of pytorch lightning on Lightning Studio (x4 CPU, AWS).

<details><summary>Script</summary>
<p>

```python
import importlib
import subprocess
import time

import torch
from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import RichProgressBar
from tabulate import tabulate
from torch.utils.data import DataLoader, Dataset

# You can extend this as needed
VERSIONS = ["2.5.1", "2.5.2", "2.5.3"]
RESULTS = []


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def benchmark(use_rich: bool):
    """Run a benchmark with or without RichProgressBar."""
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = BoringModel()

    callbacks = [RichProgressBar()] if use_rich else None

    trainer = Trainer(
        max_epochs=100,
        enable_model_summary=False,
        enable_checkpointing=False,
        logger=False,
        benchmark=False,
        callbacks=callbacks,
    )
    t0 = time.perf_counter()
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    return time.perf_counter() - t0


def run_for_version(version):
    print(f"\n=== Testing Lightning {version} ===")
    subprocess.check_call(
        ["uv", "pip", "install", f"pytorch-lightning=={version}", "-q"]
    )
    importlib.reload(importlib.import_module("pytorch_lightning"))

    # Run both variants
    no_rich_time = benchmark(use_rich=False)
    rich_time = benchmark(use_rich=True)

    RESULTS.append((version, f"{no_rich_time:.3f}", f"{rich_time:.3f}"))


if __name__ == "__main__":
    for v in VERSIONS:
        run_for_version(v)

    print("\n=== Benchmark Results ===")
    print(tabulate(RESULTS, headers=["Version", "No Rich (s)", "With Rich (s)"]))
```
</p>
</details> 

```python
=== Benchmark Results ===
Version      No Rich (s)    With Rich (s)
---------  -------------  ---------------
2.5.1             11.531           20.987
2.5.2             12.13            17.668
2.5.3             11.575           18.586
```

cc: @Borda @SkafteNicki @matsumotosan

**Comment by matsumotosan** [comment]
Running the benchmark with the `RichProgressBar` on the dev version locally raises an exception. I have an M3.

```
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/Users/shion/dev/pytorch-lightning/src/pytorch_lightning/trainer/connectors/data_connector.py:433: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=10` in the `DataLoader` to improve performance.
/Users/shion/dev/pytorch-lightning/src/pytorch_lightning/trainer/connectors/data_connector.py:433: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=10` in the `DataLoader` to improve performance.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/shion/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/live.py", line 38, in run
    self.live.refresh()
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/live.py", line 243, in refresh
    self._live_render.set_renderable(self.renderable)
                                     ^^^^^^^^^^^^^^^
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/live.py", line 221, in renderable
    renderable = Group(*[live.get_renderable() for live in live_stack])
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/live.py", line 105, in get_renderable
    self._get_renderable()
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/progress.py", line 1553, in get_renderable
    renderable = Group(*self.get_renderables())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/progress.py", line 1558, in get_renderables
    table = self.make_tasks_table(self.tasks)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/progress.py", line 1582, in make_tasks_table
    table.add_row(
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/progress.py", line 1587, in <genexpr>
    else column(task)
         ^^^^^^^^^^^^
  File "/Users/shion/dev/pytorch-lightning/.venv/lib/python3.12/site-packages/rich/progress.py", line 540, in __call__
    renderable = self.render(task)
                 ^^^^^^^^^^^^^^^^^
  File "/Users/shion/dev/pytorch-lightning/src/pytorch_lightning/callbacks/progress/rich_progress.py", line 176, in render
    self._tasks[self._current_task_id] = self._renderable_cache[self._current_task_id][1]
                                         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 0
Epoch 99/99 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32/32 0:00:00 • 0:00:00 839.48it/s  `Trainer.fit` stopped: `max_epochs=100` reached.
Epoch 99/99 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32/32 0:00:00 • 0:00:00 839.48it/s None
```

**Comment by bhimrazy** [comment]
Interesting, I’ll check it out. 
@matsumotosan, in case you’d like to duplicate the studio, I’ve published it here: https://lightning.ai/lightning-ai/studios/13937-richprogressbar-in-v1-6-is-slower-than-v1-5~01k2hqnvm6r6neccdzgq06f6fr

**Comment by GdoongMathew** [comment]
Hi @bhimrazy,

I recently stumbled upon this issue and wanted to share a few updates. Based on my profiling results, the main bottleneck appears to be in the `refresh` method.

* TQDMProgressBar:
  ```text
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     3200    0.022    0.000    1.727    0.001 tqdm_progress.py:274(on_train_batch_end)
     6400    0.020    0.000    1.476    0.000 std.py:1325(refresh)
  ```
* RichProgressBar:
  ```text
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     3200    0.013    0.000   17.485    0.005 rich_progress.py:561(on_validation_batch_end)
     6400    0.008    0.000   17.372    0.003 rich_progress.py:364(refresh)
  ```

From what I understand (and please correct me if I’m mistaken), `rich` already auto-refresh the progress bar 10 times/second when not in interactive mode ([ref](https://rich.readthedocs.io/en/latest/progress.html#auto-refresh)).
So if we change the `RichProgressBar.refresh()` method like this:

```python
class RichProgressBar(ProgressBar):
    def _init_progress(self, trainer: "pl.Trainer") -> None:
        if self.is_enabled and (self.progress is None or self._progress_stopped):
            ...
            self.progress = CustomProgress(
                *self.configure_columns(trainer),
                self._metric_component,
                auto_refresh=True,    # need to enable this, like in the PR #14360
                disable=self.is_disabled,
                console=self._console,
            )
            self.progress.start()
            ...

    def refresh(self) -> None:
        if self.progress and _IS_INTERACTIVE:
            self.progress.refresh()
```

then the benchmark results on my end are as follows:

* lightning 2.6.0 dev
  ```text
    === Benchmark Results ===
    Version      No Rich (s)    With Rich (s)
    ---------  -------------  ---------------
    2.6.0.dev          7.973           13.315
  ```

* update (autorefresh 33 / second)
  ```text
    === Benchmark Results ===
    Version      No Rich (s)    With Rich (s)
    ---------  -------------  ---------------
    2.6.0.dev          7.605             7.09
  ```

This might be a good direction to explore for improving performance. What do you think?

**Comment by GdoongMathew** [comment]
However, re-enabling `auto_refresh` does bring back #10607 tho...
