### ISSUE TITLE
Unable to run works in the `LightningList` structure on cloud

### ISSUE THREAD

**Issue by krshrimali** [Lightning-AI/pytorch-lightning#14645]
## 🐛 Bug

(as reported by @aniketmaurya)

Following error is raised:

```
[flow] 2022-09-11T08:14:06.981Z INFO: Traceback (most recent call last):
[flow] 2022-09-11T08:14:06.981Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 206, in run_lightning_flow
[flow] 2022-09-11T08:14:06.981Z     app._run()
[flow] 2022-09-11T08:14:06.981Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/core/app.py", line 427, in _run
[flow] 2022-09-11T08:14:06.981Z     done = self.run_once()
[flow] 2022-09-11T08:14:06.981Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/core/app.py", line 376, in run_once
[flow] 2022-09-11T08:14:06.981Z     self.root.run()
[flow] 2022-09-11T08:14:06.981Z   File "app.py", line 41, in run
[flow] 2022-09-11T08:14:06.981Z     model_serve.run()
[flow] 2022-09-11T08:14:06.981Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/runners/backends/backend.py", line 59, in _dynamic_run_wrapper
[flow] 2022-09-11T08:14:06.981Z     self.create_work(app, work)
[flow] 2022-09-11T08:14:06.981Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/lightning_backend.py", line 147, in create_work
[flow] 2022-09-11T08:14:06.981Z     app.work_queues[work.name].put(work)
[flow] 2022-09-11T08:14:06.981Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/core/queues.py", line 224, in put
[flow] 2022-09-11T08:14:06.981Z     value = pickle.dumps(item)
[flow] 2022-09-11T08:14:06.981Z TypeError: cannot pickle '_thread.RLock' object
```

### To Reproduce

```python
import lightning as L
from lightning_app.structures import List

class CounterWork(L.LightningWork):
    def __init__(self):
        super().__init__()
        self.counter = 0
    def run(self):
        self.counter += 1
        print(self.counter)

class RootFlow(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.list = List(*[CounterWork(), CounterWork()])
        self.work = CounterWork()
    def run(self):
        for work in self.list:
            work.run()

app = L.LightningApp(RootFlow())
```

### Expected behavior

Should work.

### Environment

lightning, version 0.5.7

### Additional context

cc: @tchaton @ethanwharris 

cc @tchaton @rohitgr7

**Comment by Borda** [comment]
@tchaton, any update so far? :rabbit:
