### ISSUE TITLE
TypeError: init() missing 1 required positional argument: 'boundaries'

### ISSUE THREAD

**Issue by liziru** [Lightning-AI/pytorch-lightning#19183]
### Bug description

I used a custom batch sampler in the 'dataloader' API to prepare the dataset for training. but I got the following error:'TypeError: init() missing 1 required positional argument: 'boundaries''

I also recorded this error in [https://github.com/Lightning-AI/pytorch-lightning/issues/19048](url). 
 
Looking forward to your reply. 

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
class DistributedBucketSampler(torch.utils.data.distributed.DistributedSampler):
"""
Maintain similar input lengths in a batch.
Length groups are specified by boundaries.
"""

def __init__(
        self,
        dataset,
        batch_size,
        boundaries,
        num_replicas=None,
        rank=None,
        shuffle=True,
        drop_last=False,
        **kwargs
):
    super().__init__(dataset, num_replicas=num_replicas, rank=rank, shuffle=shuffle, drop_last=drop_last)

    self.lengths = dataset.lengths
    self.batch_size = batch_size
    self.boundaries = boundaries

    self.buckets, self.num_samples_per_bucket = self._create_buckets()
    self.total_size = sum(self.num_samples_per_bucket)
    self.num_samples = self.total_size // self.num_replicas

def _create_buckets(self):
    buckets = [[] for _ in range(len(self.boundaries) - 1)]
    for i in range(len(self.lengths)):
        length = self.lengths[i]
        idx_bucket = self._bisect(length)
        if idx_bucket != -1:
            buckets[idx_bucket].append(i)

    for i in range(len(buckets) - 1, -1, -1):  #
        if len(buckets[i]) == 0:
            buckets.pop(i)
            self.boundaries.pop(i + 1)

    num_samples_per_bucket = []
    for i in range(len(buckets)):
        len_bucket = len(buckets[i])
        total_batch_size = self.num_replicas * self.batch_size
        rem = (
                      total_batch_size - (len_bucket % total_batch_size)
              ) % total_batch_size
        num_samples_per_bucket.append(len_bucket + rem)
    return buckets, num_samples_per_bucket

def __iter__(self):
    # deterministically shuffle based on epoch
    g = torch.Generator()
    g.manual_seed(self.epoch)
    print(33)

    indices = []
    if self.shuffle:
        for bucket in self.buckets:
            indices.append(torch.randperm(len(bucket), generator=g).tolist())
    else:
        for bucket in self.buckets:
            indices.append(list(range(len(bucket))))

    batches = []
    for i in range(len(self.buckets)):
        bucket = self.buckets[i]
        len_bucket = len(bucket)
        ids_bucket = indices[i]
        num_samples_bucket = self.num_samples_per_bucket[i]

        # add extra samples to make it evenly divisible
        rem = num_samples_bucket - len_bucket
        ids_bucket = (
                ids_bucket
                + ids_bucket * (rem // len_bucket)
                + ids_bucket[: (rem % len_bucket)]
        )

        # subsample
        ids_bucket = ids_bucket[self.rank:: self.num_replicas]

        # batching
        for j in range(len(ids_bucket) // self.batch_size):
            batch = [
                bucket[idx]
                for idx in ids_bucket[
                           j * self.batch_size: (j + 1) * self.batch_size
                           ]
            ]
            batches.append(batch)

    if self.shuffle:
        batch_ids = torch.randperm(len(batches), generator=g).tolist()
        batches = [batches[i] for i in batch_ids]
    self.batches = batches

    assert len(self.batches) * self.batch_size == self.num_samples
    return iter(self.batches)

def _bisect(self, x, lo=0, hi=None):
    if hi is None:
        hi = len(self.boundaries) - 1

    if hi > lo:
        mid = (hi + lo) // 2
        if self.boundaries[mid] < x and x <= self.boundaries[mid + 1]:
            return mid
        elif x <= self.boundaries[mid]:
            return self._bisect(x, lo, mid)
        else:
            return self._bisect(x, mid + 1, hi)
    else:
        return -1

def __len__(self):
    return self.num_samples // self.batch_size
```

### Error messages and logs

```
Traceback (most recent call last):
File "/home/lee/Desktop/workspace2/project/tts/RVC/c/training/train.py", line 308, in
main(conf, exp_dir, training_dir, bool(args.use_pretrain))
File "/home/lee/Desktop/workspace2/project/tts/RVC/c/training/train.py", line 230, in main
trainer.fit(system)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
call._call_and_handle_interrupt(
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
return function(*args, **kwargs)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
self._run(model, ckpt_path=ckpt_path)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
results = self._run_stage()
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
self.fit_loop.run()
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 194, in run
self.setup_data()
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 238, in setup_data
dl = _process_dataloader(trainer, trainer_fn, stage, dl)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 501, in _process_dataloader
dataloader = trainer._data_connector._prepare_dataloader(dataloader, shuffle=is_shuffled, mode=stage)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 207, in _prepare_dataloader
return _update_dataloader(dataloader, sampler, mode=mode)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 133, in _update_dataloader
dl_args, dl_kwargs = _get_dataloader_init_args_and_kwargs(dataloader, sampler, mode)
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 192, in _get_dataloader_init_args_and_kwargs
dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode))
File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 282, in _dataloader_init_kwargs_resolve_sampler
batch_sampler = batch_sampler_cls(
TypeError: init() missing 1 required positional argument: 'boundaries'

Process finished with exit code 1
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.1.0+cu118
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): ubuntu 20.04
#- CUDA/cuDNN version: cu118
#- GPU models and configuration: rtx1080ti
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

### More info
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/34911790/72e4a795-be67-48d0-9cae-176cfbe0d941)

_No response_

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
@liziru I put your code in an example. Could you please modify it to make it fail like you show? I also left some questions in the code, can you take a look?

```py
import torch
from lightning.pytorch import LightningModule, Trainer
from torch.utils.data import DataLoader, Dataset


class DistributedBucketSampler(torch.utils.data.distributed.DistributedSampler):
    """
    Maintain similar input lengths in a batch.
    Length groups are specified by boundaries.
    """

    def __init__(
        self,
        dataset,
        batch_size,
        boundaries,
        num_replicas=None,
        rank=None,
        shuffle=True,
        drop_last=False,
        **kwargs  # TODO: WHY ARE KWARGS IGNORED?
    ):
        super().__init__(dataset, num_replicas=num_replicas, rank=rank, shuffle=shuffle, drop_last=drop_last)

        self.lengths = dataset.lengths # TODO: WHAT IS THIS?
        self.batch_size = batch_size
        self.boundaries = boundaries

        self.buckets, self.num_samples_per_bucket = self._create_buckets()
        self.total_size = sum(self.num_samples_per_bucket)
        self.num_samples = self.total_size // self.num_replicas

    def _create_buckets(self):
        buckets = [[] for _ in range(len(self.boundaries) - 1)]
        for i in range(len(self.lengths)):
            length = self.lengths[i]
            idx_bucket = self._bisect(length)
            if idx_bucket != -1:
                buckets[idx_bucket].append(i)

        for i in range(len(buckets) - 1, -1, -1):  #
            if len(buckets[i]) == 0:
                buckets.pop(i)
                self.boundaries.pop(i + 1)

        num_samples_per_bucket = []
        for i in range(len(buckets)):
            len_bucket = len(buckets[i])
            total_batch_size = self.num_replicas * self.batch_size
            rem = (
                          total_batch_size - (len_bucket % total_batch_size)
                  ) % total_batch_size
            num_samples_per_bucket.append(len_bucket + rem)
        return buckets, num_samples_per_bucket

    def __iter__(self):
        # deterministically shuffle based on epoch
        g = torch.Generator()
        g.manual_seed(self.epoch)
        print(33)

        indices = []
        if self.shuffle:
            for bucket in self.buckets:
                indices.append(torch.randperm(len(bucket), generator=g).tolist())
        else:
            for bucket in self.buckets:
                indices.append(list(range(len(bucket))))

        batches = []
        for i in range(len(self.buckets)):
            bucket = self.buckets[i]
            len_bucket = len(bucket)
            ids_bucket = indices[i]
            num_samples_bucket = self.num_samples_per_bucket[i]

            # add extra samples to make it evenly divisible
            rem = num_samples_bucket - len_bucket
            ids_bucket = (
                    ids_bucket
                    + ids_bucket * (rem // len_bucket)
                    + ids_bucket[: (rem % len_bucket)]
            )

            # subsample
            ids_bucket = ids_bucket[self.rank:: self.num_replicas]

            # batching
            for j in range(len(ids_bucket) // self.batch_size):
                batch = [
                    bucket[idx]
                    for idx in ids_bucket[
                               j * self.batch_size: (j + 1) * self.batch_size
                               ]
                ]
                batches.append(batch)

        if self.shuffle:
            batch_ids = torch.randperm(len(batches), generator=g).tolist()
            batches = [batches[i] for i in batch_ids]
        self.batches = batches

        assert len(self.batches) * self.batch_size == self.num_samples
        return iter(self.batches)

    def _bisect(self, x, lo=0, hi=None):
        if hi is None:
            hi = len(self.boundaries) - 1

        if hi > lo:
            mid = (hi + lo) // 2
            if self.boundaries[mid] < x and x <= self.boundaries[mid + 1]:
                return mid
            elif x <= self.boundaries[mid]:
                return self._bisect(x, lo, mid)
            else:
                return self._bisect(x, mid + 1, hi)
        else:
            return -1

    def __len__(self):
        return self.num_samples // self.batch_size


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
        self.lengths = # FIXME: HOW DO I NEED TO DEFINE THIS?

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

    def train_dataloader(self):
        dataset = RandomDataset(32, 64)
        sampler = DistributedBucketSampler(dataset, batch_size=2, boundaries=[0.5, 1.0, 1.5])
        loader = DataLoader(dataset, batch_size=2, sampler=sampler)
        return loader


def run():
    model = BoringModel()
    trainer = Trainer(
        devices=2,
        accelerator="cpu",
        max_epochs=1,
    )
    trainer.fit(model)


if __name__ == "__main__":
    run()

```

**Comment by liziru** [comment]
> @liziru I put your code in an example. Could you please modify it to make it fail like you show? I also left some questions in the code, can you take a look?
> 
> ```python
> import torch
> from lightning.pytorch import LightningModule, Trainer
> from torch.utils.data import DataLoader, Dataset
> 
> 
> class DistributedBucketSampler(torch.utils.data.distributed.DistributedSampler):
>     """
>     Maintain similar input lengths in a batch.
>     Length groups are specified by boundaries.
>     """
> 
>     def __init__(
>         self,
>         dataset,
>         batch_size,
>         boundaries,
>         num_replicas=None,
>         rank=None,
>         shuffle=True,
>         drop_last=False,
>         **kwargs  # TODO: WHY ARE KWARGS IGNORED?
>     ):
>         super().__init__(dataset, num_replicas=num_replicas, rank=rank, shuffle=shuffle, drop_last=drop_last)
> 
>         self.lengths = dataset.lengths # TODO: WHAT IS THIS?
>         self.batch_size = batch_size
>         self.boundaries = boundaries
> 
>         self.buckets, self.num_samples_per_bucket = self._create_buckets()
>         self.total_size = sum(self.num_samples_per_bucket)
>         self.num_samples = self.total_size // self.num_replicas
> 
>     def _create_buckets(self):
>         buckets = [[] for _ in range(len(self.boundaries) - 1)]
>         for i in range(len(self.lengths)):
>             length = self.lengths[i]
>             idx_bucket = self._bisect(length)
>             if idx_bucket != -1:
>                 buckets[idx_bucket].append(i)
> 
>         for i in range(len(buckets) - 1, -1, -1):  #
>             if len(buckets[i]) == 0:
>                 buckets.pop(i)
>                 self.boundaries.pop(i + 1)
> 
>         num_samples_per_bucket = []
>         for i in range(len(buckets)):
>             len_bucket = len(buckets[i])
>             total_batch_size = self.num_replicas * self.batch_size
>             rem = (
>                           total_batch_size - (len_bucket % total_batch_size)
>                   ) % total_batch_size
>             num_samples_per_bucket.append(len_bucket + rem)
>         return buckets, num_samples_per_bucket
> 
>     def __iter__(self):
>         # deterministically shuffle based on epoch
>         g = torch.Generator()
>         g.manual_seed(self.epoch)
>         print(33)
> 
>         indices = []
>         if self.shuffle:
>             for bucket in self.buckets:
>                 indices.append(torch.randperm(len(bucket), generator=g).tolist())
>         else:
>             for bucket in self.buckets:
>                 indices.append(list(range(len(bucket))))
> 
>         batches = []
>         for i in range(len(self.buckets)):
>             bucket = self.buckets[i]
>             len_bucket = len(bucket)
>             ids_bucket = indices[i]
>             num_samples_bucket = self.num_samples_per_bucket[i]
> 
>             # add extra samples to make it evenly divisible
>             rem = num_samples_bucket - len_bucket
>             ids_bucket = (
>                     ids_bucket
>                     + ids_bucket * (rem // len_bucket)
>                     + ids_bucket[: (rem % len_bucket)]
>             )
> 
>             # subsample
>             ids_bucket = ids_bucket[self.rank:: self.num_replicas]
> 
>             # batching
>             for j in range(len(ids_bucket) // self.batch_size):
>                 batch = [
>                     bucket[idx]
>                     for idx in ids_bucket[
>                                j * self.batch_size: (j + 1) * self.batch_size
>                                ]
>                 ]
>                 batches.append(batch)
> 
>         if self.shuffle:
>             batch_ids = torch.randperm(len(batches), generator=g).tolist()
>             batches = [batches[i] for i in batch_ids]
>         self.batches = batches
> 
>         assert len(self.batches) * self.batch_size == self.num_samples
>         return iter(self.batches)
> 
>     def _bisect(self, x, lo=0, hi=None):
>         if hi is None:
>             hi = len(self.boundaries) - 1
> 
>         if hi > lo:
>             mid = (hi + lo) // 2
>             if self.boundaries[mid] < x and x <= self.boundaries[mid + 1]:
>                 return mid
>             elif x <= self.boundaries[mid]:
>                 return self._bisect(x, lo, mid)
>             else:
>                 return self._bisect(x, mid + 1, hi)
>         else:
>             return -1
> 
>     def __len__(self):
>         return self.num_samples // self.batch_size
> 
> 
> class RandomDataset(Dataset):
>     def __init__(self, size, length):
>         self.len = length
>         self.data = torch.randn(length, size)
>         self.lengths = # FIXME: HOW DO I NEED TO DEFINE THIS?
> 
>     def __getitem__(self, index):
>         return self.data[index]
> 
>     def __len__(self):
>         return self.len
> 
> 
> class BoringModel(LightningModule):
>     def __init__(self):
>         super().__init__()
>         self.layer = torch.nn.Linear(32, 2)
> 
>     def forward(self, x):
>         return self.layer(x)
> 
>     def training_step(self, batch, batch_idx):
>         loss = self(batch).sum()
>         self.log("train_loss", loss)
>         return {"loss": loss}
> 
>     def configure_optimizers(self):
>         return torch.optim.SGD(self.layer.parameters(), lr=0.1)
> 
>     def train_dataloader(self):
>         dataset = RandomDataset(32, 64)
>         sampler = DistributedBucketSampler(dataset, batch_size=2, boundaries=[0.5, 1.0, 1.5])
>         loader = DataLoader(dataset, batch_size=2, sampler=sampler)
>         return loader
> 
> 
> def run():
>     model = BoringModel()
>     trainer = Trainer(
>         devices=2,
>         accelerator="cpu",
>         max_epochs=1,
>     )
>     trainer.fit(model)
> 
> 
> if __name__ == "__main__":
>     run()
> ```

Thanks for your reply. The following code works, but the same error appeared when using "batch_sampler" instead of "sampler" in dataloader API.
```
import torch
# from lightning.pytorch import LightningModule, Trainer
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning import Trainer, LightningModule


class DistributedBucketSampler(torch.utils.data.distributed.DistributedSampler):
    """
    Maintain similar input lengths in a batch.
    Length groups are specified by boundaries.
    """

    def __init__(
            self,
            dataset,
            batch_size,
            boundaries,
            num_replicas=None,
            rank=None,
            shuffle=True,
            drop_last=False,
            **kwargs  # TODO: WHY ARE KWARGS IGNORED?
    ):
        super().__init__(dataset, num_replicas=num_replicas, rank=rank, shuffle=shuffle, drop_last=drop_last)

        self.lengths = dataset.lengths  # TODO: WHAT IS THIS?
        self.batch_size = batch_size
        self.boundaries = boundaries

        self.buckets, self.num_samples_per_bucket = self._create_buckets()
        self.total_size = sum(self.num_samples_per_bucket)
        self.num_samples = self.total_size // self.num_replicas

    def _create_buckets(self):
        buckets = [[] for _ in range(len(self.boundaries) - 1)]
        for i in range(len(self.lengths)):
            length = self.lengths[i]
            idx_bucket = self._bisect(length)
            if idx_bucket != -1:
                buckets[idx_bucket].append(i)

        for i in range(len(buckets) - 1, -1, -1):  #
            if len(buckets[i]) == 0:
                buckets.pop(i)
                self.boundaries.pop(i + 1)

        num_samples_per_bucket = []
        for i in range(len(buckets)):
            len_bucket = len(buckets[i])
            total_batch_size = self.num_replicas * self.batch_size
            rem = (
                          total_batch_size - (len_bucket % total_batch_size)
                  ) % total_batch_size
            num_samples_per_bucket.append(len_bucket + rem)
        return buckets, num_samples_per_bucket

    def __iter__(self):
        # deterministically shuffle based on epoch
        g = torch.Generator()
        g.manual_seed(self.epoch)

        indices = []
        if self.shuffle:
            for bucket in self.buckets:
                indices.append(torch.randperm(len(bucket), generator=g).tolist())
        else:
            for bucket in self.buckets:
                indices.append(list(range(len(bucket))))

        batches = []
        for i in range(len(self.buckets)):
            bucket = self.buckets[i]
            len_bucket = len(bucket)
            ids_bucket = indices[i]
            num_samples_bucket = self.num_samples_per_bucket[i]

            # add extra samples to make it evenly divisible
            rem = num_samples_bucket - len_bucket
            ids_bucket = (
                    ids_bucket
                    + ids_bucket * (rem // len_bucket)
                    + ids_bucket[: (rem % len_bucket)]
            )

            # subsample
            ids_bucket = ids_bucket[self.rank:: self.num_replicas]

            # batching
            for j in range(len(ids_bucket) // self.batch_size):
                batch = [
                    bucket[idx]
                    for idx in ids_bucket[
                               j * self.batch_size: (j + 1) * self.batch_size
                               ]
                ]
                batches.append(batch)

        if self.shuffle:
            batch_ids = torch.randperm(len(batches), generator=g).tolist()
            batches = [batches[i] for i in batch_ids]
        self.batches = batches

        assert len(self.batches) * self.batch_size == self.num_samples
        return iter(self.batches)

    def _bisect(self, x, lo=0, hi=None):
        if hi is None:
            hi = len(self.boundaries) - 1

        if hi > lo:
            mid = (hi + lo) // 2
            if self.boundaries[mid] < x and x <= self.boundaries[mid + 1]:
                return mid
            elif x <= self.boundaries[mid]:
                return self._bisect(x, lo, mid)
            else:
                return self._bisect(x, mid + 1, hi)
        else:
            return -1

    def __len__(self):
        return self.num_samples // self.batch_size


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
        self.lengths = [200, 200, 200, 163, 200, 200, 200, 200, 200, 200, 200, 175, 200, 200, 200, 181, 200, 200, 135,
                        200, 192, 175, 192, 174, 200, 199, 200, 183, 199]  # feature length

    def __getitem__(self, index):
        print(index)
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

    def train_dataloader(self):
        dataset = RandomDataset(32, 64)
        sampler = DistributedBucketSampler(dataset, 4,
                                           [100, 200, 300, 400,],
                                           num_replicas=1, rank=0, shuffle=True,
                                           )
        # 'sampler' works
        loader = DataLoader(dataset, batch_size=4, sampler=sampler)
        # 'batch_sampler' dosenot work
        # loader = DataLoader(dataset, batch_sampler=sampler)
        return loader


def run():
    model = BoringModel()
    trainer = Trainer(
        devices=2,
        accelerator="cpu",
        max_epochs=10000,
    )
    trainer.fit(model)


if __name__ == "__main__":
    run()
```

**Comment by awaelchli** [comment]
@liziru In this case, since you want to implement a custom batch sampler and you already have it distributed, then Lightning does not need to replace it. So in this case simply set

```py
trainer = Trainer(..., use_distributed_sampler=False)
```

and Lightning won't touch it.

**Comment by awaelchli** [comment]
Does that work for you @liziru?

**Comment by liziru** [comment]
> Does that work for you @liziru?

Yes, it works. Thank you very much.
