### ISSUE TITLE
Issue with bf16-true training with compiled model.

### ISSUE THREAD

**Issue by haydn-jones** [Lightning-AI/pytorch-lightning#19207]
### Bug description

It looks like strange behavior is happening when I use `precision='bfloat16-true'` in the trainer with a compiled model. Inductor will throw an error complaining the dtype of query and key in `F.scaled_dot_product_attention`. This does not happen when I use plain PyTorch. I've attached code that reproduces this issue. It's probably not too useful, but here is the stack trace

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
import lightning as L
import torch
import torch.nn.functional as F
import torch.nn as nn

torch.set_float32_matmul_precision("medium")


class VAE(L.LightningModule):
    def __init__(
        self,
        d_model: int = 128,
        nhead: int = 8,
    ):
        super().__init__()

        self.tok_emb = nn.Embedding(128, embedding_dim=d_model)
        self.cross_attn = MultiheadAttention(d_model, nhead)

    def forward(self, tokens):
        embed = self.tok_emb(tokens)
        z = torch.randn(embed.shape[0], 4, embed.shape[2], device=embed.device, dtype=embed.dtype)

        logits = self.cross_attn(embed, z, z)
        return {"loss": logits.mean(), "z": z}

    def training_step(self, tokens):
        tokens = torch.vstack(tokens)
        return self(tokens)

    def configure_optimizers(self):
        opt = torch.optim.AdamW(self.parameters(), lr=3e-4, betas=(0.9, 0.95))
        sched = torch.optim.lr_scheduler.LambdaLR(opt, lambda step: min(step / 4279, 1.0))
        return {
            "optimizer": opt,
            "lr_scheduler": {
                "scheduler": sched,
                "interval": "step",
            },
        }


class MultiheadAttention(nn.Module):
    def __init__(
        self,
        embed_dim: int,
        heads: int,
    ):
        super().__init__()

        self.embed_size = embed_dim
        self.num_heads = heads
        self.head_dim = embed_dim // heads

        assert self.head_dim * heads == embed_dim, "Embedding size needs to be divisible by heads"

        self.q_proj = nn.Linear(self.embed_size, self.embed_size)
        self.k_proj = nn.Linear(self.embed_size, self.embed_size)
        self.v_proj = nn.Linear(self.embed_size, self.embed_size)

    def forward(self, query, key, value):
        N = query.shape[0]

        q = query.view(N, -1, self.num_heads, self.head_dim).swapaxes(1, 2)
        k = key.view(N, -1, self.num_heads, self.head_dim).swapaxes(1, 2)
        v = value.view(N, -1, self.num_heads, self.head_dim).swapaxes(1, 2)

        attn = F.scaled_dot_product_attention(q, k, v)
        attn = attn.swapaxes(1, 2).reshape(N, -1, self.embed_size)
        return attn


model = VAE()
model = torch.compile(model)
data = [torch.randint(0, 128, (512, 128)) for _ in range(100)]

trainer = L.Trainer(
    accelerator="gpu",
    devices=1,
    max_epochs=2000,
    precision="bf16-true",
)
try:
    trainer.fit(model, train_dataloaders=data)
except Exception as e:
    print(e)

# Now train with standard pytorch

print("Training with standard pytorch")
model = VAE().to(device="cuda", dtype=torch.bfloat16)
model = torch.compile(model)
tokens = torch.randint(0, 128, (512, 128), device=model.device)

opt = model.configure_optimizers()["optimizer"]
loss = model(tokens)
loss["loss"].backward()
opt.step()
print(f"Done: {loss['loss'].dtype}")
```

### Error messages and logs

```Python
Traceback (most recent call last):
  File "/home/supa/lin_storage/research/MolFormers/train.py", line 84, in <module>
    trainer.fit(model, train_dataloaders=data)
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/core/module.py", line 1291, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/plugins/precision/precision.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/optim/adamw.py", line 164, in step
    loss = closure()
           ^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/plugins/precision/precision.py", line 104, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
                  ^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 382, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 434, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/supa/lin_storage/research/MolFormers/train.py", line 27, in training_step
    def training_step(self, tokens):
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 434, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 901, in forward
    return compiled_fn(full_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/utils.py", line 81, in g
    return f(*args)
           ^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 83, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/utils.py", line 105, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
                            ^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/utils.py", line 81, in g
    return f(*args)
           ^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 408, in forward
    fw_outs = call_func_at_runtime_with_args(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/utils.py", line 105, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
                            ^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 112, in deferred_for_real_inputs
    return inner_debug_fn(real_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 162, in inner_debug_fn
    out = inner_compiled_fn(real_inputs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 863, in __call__
    return self.get_current_callable()(inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 608, in run
    return model(new_inputs)
           ^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 891, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/torchinductor_supa/uw/cuwmlhweup7afweop5aj2z3xfvbe3zk5fjoy7oa2wg2cd76mbbno.py", line 1429, in call
    buf104 = aten._scaled_dot_product_flash_attention(reinterpret_tensor(buf103, (100, 8, 128, 16), (16384, 16, 128, 1), 0), reinterpret_tensor(buf102, (100, 8, 4, 16), (512, 16, 128, 1), 0), reinterpret_tensor(buf102, (100, 8, 4, 16), (512, 16, 128, 1), 0), scale=0.25)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supa/miniforge3/envs/molformer_nightly/lib/python3.11/site-packages/torch/_ops.py", line 826, in __call__
    return self_._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: query and key must have the same dtype
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca

**Comment by awaelchli** [comment]
@haydn-jones Here is the PyTorch code that is equivalent to what the trainer does, and reproduces the same dtype error:

```py
print("Training with standard pytorch")
model = VAE().to(device="cuda", dtype=torch.bfloat16)
model = torch.compile(model)
tokens = torch.randint(0, 128, (512, 128), device=model.device)

opt = model.configure_optimizers()["optimizer"]
torch.set_default_dtype(torch.bfloat16)  # < -------- THIS LINE ADDED
loss = model(tokens)
torch.set_default_dtype(torch.float32)   # < -------- THIS LINE ADDED
loss["loss"].backward()
opt.step()
print(f"Done: {loss['loss'].dtype}")
```

Here is the code in the bf16 plugin that does that (during forward):
https://github.com/Lightning-AI/pytorch-lightning/blob/858803236e02653fadd25f2fe3c01ad1eadb5311/src/lightning/pytorch/plugins/precision/half.py#L55-L66

The issue seems to occur only when torch-compiled, so I suggest we report this to PyTorch. Do you agree @haydn-jones?

Happy holidays

**Comment by haydn-jones** [comment]
Interesting, thank you. I'll play around with the code you posted, though I suspect its due to the `torch.set_default_dtype(torch.float32)` before backward is called. I'll take a look.

**Comment by awaelchli** [comment]
I added `torch.set_default_dtype(torch.float32)` just for completeness, it is not necessary to reproduce the issue.

**Comment by awaelchli** [comment]
I reported this in https://github.com/pytorch/pytorch/issues/119162
