### ISSUE TITLE
No module named 'binascii

### ISSUE THREAD

**Issue by kanydao** [Lightning-AI/pytorch-lightning#19306]
### Bug description

```
Traceback (most recent call last):
  File "train/train_vqgan.py", line 7, in <module>
    import pytorch_lightning as pl
  File "/home/zhmg/miniconda3/envs/medicaldiffusion/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 6, in <module>
    from lightning_utilities import module_available
  File "/home/zhmg/miniconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_utilities/__init__.py", line 6, in <module>
    from lightning_utilities.core.apply_func import apply_to_collection
  File "/home/zhmg/miniconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_utilities/core/__init__.py", line 4, in <module>
    from lightning_utilities.core.imports import compare_version, module_available
  File "/home/zhmg/miniconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_utilities/core/imports.py", line 13, in <module>
    import pkg_resources
  File "/home/zhmg/miniconda3/envs/medicaldiffusion/lib/python3.8/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/lib/python3.8/zipfile.py", line 6, in <module>
    import binascii
ModuleNotFoundError: No module named 'binascii
```

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@kanydao Could you please share the environment as instructed by the bug report instructions?

```
wget https://raw.githubusercontent.com/Lightning-AI/lightning/master/requirements/collect_env_details.py
python collect_env_details.py
```

For this problem it is essential, otherwise we won't be able to help you.

**Comment by awaelchli** [comment]
I think one thing you can try is to update the `setuptools` package.
https://bugs.python.org/issue46579

**Comment by kanydao** [comment]
> I think one thing you can try is to update the `setuptools` package. https://bugs.python.org/issue46579

Thank you very much, after I deleted the environment and reinstalled python, the problem was solved.
