### ISSUE TITLE
Issue with _restricted_classmethod_impl Triggering TypeError on inspect.getmembers Call

### ISSUE THREAD

**Issue by lauritsf** [Lightning-AI/pytorch-lightning#19329]
### Bug description

When using `inspect.getmembers` on a `LightningModule` instance (or any class using `_restricted_classmethod_impl`), a `TypeError` is incorrectly raised. This issue was introduced in PR #18432 ("Raise exception when load_from_checkpoint called from instance") and is present in version 2.1.1 onwards. The current implementation triggers the check during attribute access rather than at the time of method call.

### What version are you seeing the problem on?

v2.1, master

### How to reproduce the bug

```python
import inspect
from pytorch_lightning.utilities.model_helpers import _restricted_classmethod_impl

class ExampleClass:
    @_restricted_classmethod_impl
    def example_method(cls):
        print("hello")

if __name__ = "__main__":
    inspect.getmembers(ExampleClass())
```

### Error messages and logs

```
Traceback (most recent call last):
  File "PATH/file.py", line 10, in <module>
    inspect.getmembers(ExampleClass())
  File "/home/USER/.conda/envs/python311/lib/python3.11/inspect.py", line 595, in getmembers
    return _getmembers(object, predicate, getattr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.conda/envs/python311/lib/python3.11/inspect.py", line 573, in _getmembers
    value = getter(object, key)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.conda/envs/python311/lib/python3.11/site-packages/pytorch_lightning/utilities/model_helpers.py", line 93, in __get__
    raise TypeError(
TypeError: The classmethod `ExampleClass.example_method` cannot be called on an instance. Please call it on the class type and make sure the return value is used.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningModule
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1.3
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 2.0): 2.1.2
#- Python version (e.g., 3.9): 3.11
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

### More info

**Suggested Solution**

Modify `_restricted_classmethod_impl` to perform the instance check only when the method is actually called. Proposed change:

```python
class _restricted_classmethod_impl(Generic[_T, _P, _R_co]):
    # ... [existing class documentation]

    def __init__(self, method: Callable[Concatenate[_T, _P], _R_co]) -> None:
        self.method = method

    def __get__(self, instance: Optional[_T], cls: Type[_T]) -> Callable[_P, _R_co]:
        def wrapper(*args, **kwargs):
            # Workaround for https://github.com/pytorch/pytorch/issues/67146
            is_scripting = any(os.path.join("torch", "jit") in frameinfo.filename for frameinfo in inspect.stack())
            if instance is not None and not is_scripting:
                raise TypeError(
                    f"The classmethod `{cls.__name__}.{self.method.__name__}` cannot be called on an instance."
                    " Please call it on the class type and make sure the return value is used."
                )
            return self.method(cls, *args, **kwargs)
        
        return wrapper

**Comment by awaelchli** [comment]
@lauritsf Thanks for posting the bug report. Would you like to submit your proposed change as a PR? We can then let all the tests run and see if that works (I don't see any obvious issue with your proposal).
