### ISSUE TITLE
DDP strategy raises RuntimeError: Please call `iter(combined_loader)` first.

### ISSUE THREAD

**Issue by alexge233** [Lightning-AI/pytorch-lightning#19373]
### Bug description

I'm using a vanilla BERT implemented from pytorch blocks, and lightning to wrap around it.
When I run without DDP, everything goes as planned.
When I try with DDP, I get a Runtime Error.
Switching to `ddp_spawn` works without the above issue.
This is with pytorch 2.1.2 and lightning 2.1.3

### What version are you seeing the problem on?

2.1.3

### How to reproduce the bug

```python
strategy = DDPStrategy(static_graph=True)
 trainer = L.Trainer(
        inference_mode=False,
        strategy= strategy,
        num_nodes=1,
        devices=2,
        callbacks=callbacks,
        check_val_every_n_epoch=1,
        enable_checkpointing=True,
        fast_dev_run=True,
        detect_anomaly=True,
        accumulate_grad_batches=8,
        gradient_clip_val=0.5,
        gradient_clip_algorithm="value",
        min_epochs=100,
        max_epochs=1000,
        precision="bf16-mixed",
        enable_progress_bar=True,
        logger = ml_logger,
    )
    with trainer.init_module():
        model = VanillaModel()
        trainer.fit(
            model
        )
```

### Error messages and logs

```
traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 194, in run
    self.setup_data()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 258, in setup_data
    iter(self._data_fetcher)  # creates the iterator inside the fetcher
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 99, in __iter__
    super().__iter__()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 48, in __iter__
    self.iterator = iter(self.combined_loader)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 335, in __iter__
    iter(iterator)
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 87, in __iter__
    super().__iter__()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 40, in __iter__
    self.iterators = [iter(iterable) for iterable in self.iterables]
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 40, in <listcomp>
    self.iterators = [iter(iterable) for iterable in self.iterables]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 433, in __iter__
    self._iterator = self._get_iterator()
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1084, in __init__
    self._reset(loader, first_iter=True)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1117, in _reset
    self._try_put_index()
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1351, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 282, in __iter__
    for idx in self.sampler:
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 101, in __iter__
    indices = torch.randperm(len(self.dataset), generator=g).tolist()  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/fabric/utilities/init.py", line 51, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/sjp-ml-pipeline/scripts/train_vanilla.py", line 96, in <module>
    main()
  File "/root/sjp-ml-pipeline/scripts/train_vanilla.py", line 91, in main
    trainer.fit(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 68, in _call_and_handle_interrupt
    trainer._teardown()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _teardown
    loop.teardown()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 407, in teardown
    self._data_fetcher.teardown()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 75, in teardown
    self.reset()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 134, in reset
    super().reset()
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 71, in reset
    self.length = sized_len(self.combined_loader)
  File "/usr/local/lib/python3.10/site-packages/lightning/fabric/utilities/data.py", line 51, in sized_len
    length = len(dataloader)  # type: ignore [arg-type]
  File "/usr/local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 342, in __len__
    raise RuntimeError("Please call `iter(combined_loader)` first.")
RuntimeError: Please call `iter(combined_loader)` first.
```

### Environment

This is in AWS `base-pyth-ml-g5-48xlarge` with 8 GPUs.

### More info

I've tried to wrap my DataLoaders like such but it didn't seem to make a difference:

```
    return DataLoader(
            train,
            persistent_workers=True,
            pin_memory=True,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            generator=torch.Generator(device=self.device)
        )
```

**Comment by awaelchli** [comment]
@alexge233 Note that the error you got is not the real error. If you look at the stack above it, you see the real error:

```
  File "/usr/local/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 101, in __iter__
    indices = torch.randperm(len(self.dataset), generator=g).tolist()  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/fabric/utilities/init.py", line 51, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```

Perhaps remove the generator from the DataLoader?
It is because you are passing a generator to the DataLoader with device cuda, but that doesn't make sense. The dataloader needs its indices on CPU. So just remove that generator or pass it without the device argument.

**Comment by alexge233** [comment]
@awaelchli Thanks a lot for the prompt response. I have removed the offending lines, meaning there is no Generator, nor is there any line of code to place the data on the GPU. I am still getting the exact same error.

**Comment by alexge233** [comment]
Of course, here it is.

```
import lightning as L
from torch.utils.data import Dataset, DataLoader

class TextAdviceDataModule(L.LightningDataModule):
    def __init__(self, batch: int, workers: int, dataset_dir: str):
        super(TextAdviceDataModule).__init__()
        self.dataset_dir = dataset_dir
        self.batch_size = batch
        self.num_workers = workers
        self.persistance = False
        if workers > 0:
            self.persistance = True

    def train_dataloader(self) -> DataLoader:
        train = TextAdviceDataset(
            f"{self.dataset_dir}text2text_trainset_pytorch.pt"
        )
        return DataLoader(
            train,
            persistent_workers=self.persistance,
            pin_memory=True,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
        )

    def val_dataloader(self) -> DataLoader:
        validate = TextAdviceDataset(
            f"{self.dataset_dir}text2text_valset_pytorch.pt"
        )
        return DataLoader(
            validate,
            persistent_workers=self.persistance,
            pin_memory=True,
            batch_size=self.batch_size,
            num_workers=self.num_workers
        )

    def test_dataloader(self) -> DataLoader:       
        test = TextAdviceDataset(
            f"{self.dataset_dir}text2text_testset_pytorch.pt"
        )
        return DataLoader(
            test,
            persistent_workers=self.persistance,
            pin_memory=True,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
        )
```

And the class `TextAdviceDataset`:

```
class TextAdviceDataset(Dataset):
    def __init__(self, filename: str):
        data = torch.load(filename)
        self.input_ids = data["input_ids"]
        self.input_masks = data["input_masks"]
        self.output_ids = data["output_ids"]
        self.output_masks = data["output_masks"]
        print(f"Loaded {len(self.input_ids)} from {filename}")

    def __len__(self) -> int:
        return len(self.input_ids)

    def __getitem__(self,
                    idx: int
                    ) -> Tuple[torch.Tensor,
                               torch.Tensor,
                               torch.Tensor,
                               torch.Tensor]:
        """ Get a Sample
        Returns:
            Tuple of tensors, where tensors are:
            - input token ids
            - input attention mask
            - output token ids
            - output attention mask
        """
        return (self.input_ids[idx],
                self.input_masks[idx],
                self.output_ids[idx],
                self.output_masks[idx])
```

**Comment by alexge233** [comment]
Sorry, I forgot to mention. 

```python
>>> batch_size = 1
>>> data_module = dataloader.TextAdviceDataModule(batch  = batch_size, 
...                                               workers = 0, 
...                                               dataset_dir = "assets/local/")
>>> train_dataloaders = data_module.train_dataloader()
Loaded 41584 from assets/local/text2text_trainset_pytorch.pt
>>> print(len(train_dataloaders))
41584
>> val_dataloaders = data_module.val_dataloader()
Loaded 10397 from assets/local/text2text_valset_pytorch.pt
>>> print(len(val_dataloaders))
10397
```

**Comment by awaelchli** [comment]
Hey @alexge233 

Ae you aware that you are applying `with trainer.init_module():` over more than just the model? This should go ONLY over the model creation (as the name suggests), not anything else. This might be the explanation why you see the weird error, because that would mean the tensors in your dataset you load get converted to CUDA, but that's not what you want. Please only apply it over the model like so:

```py
with trainer.init_module():
    model = VanillaBertModel()
   # nothing else here
   
# continue with rest of code outside here!
```

Now, I couldn't verify this because the code you shared has still missing pieces. I don't have your dataset, and the exact model definition. I can mock this out and provide dummy values, but it may not reproduce the problem if I don't have the same definitions as you have. If my suggestion about init_module doesn't solve your issue, I would really appreciate if you could share a self contained repro.

**Comment by alexge233** [comment]
@awaelchli I did not know that! I apologise, you are indeed correct, as soon as I moved the code outside the `with` statement the error went away. Thank you very much!
