### ISSUE TITLE
'TwoStreamBatchSampler' object has no attribute 'batch_size'

### ISSUE THREAD

**Issue by Hanshenggao** [Lightning-AI/pytorch-lightning#19371]
### Bug description

When I was using the batch_sampler I created myself, I had the following problem. What caused it?

### What version are you seeing the problem on?

v1.8

### How to reproduce the bug

```python
class TwoStreamBatchSampler(Sampler):
    """Iterate two sets of indices

    An 'epoch' is one iteration through the primary indices.
    During the epoch, the secondary indices are iterated through
    as many times as needed.
    """
    def __init__(self, primary_indices, secondary_indices, primary_batch_size, secondary_batch_size):
        self.primary_indices = primary_indices
        self.secondary_indices = secondary_indices
        self.secondary_batch_size = secondary_batch_size
        self.primary_batch_size = primary_batch_size
        assert len(self.primary_indices) >= self.primary_batch_size > 0
        assert len(self.secondary_indices) >= self.secondary_batch_size > 0

    def __iter__(self):
        primary_iter = iterate_once(self.primary_indices)
        secondary_iter = iterate_eternally(self.secondary_indices)
        return (
            primary_batch + secondary_batch
            for (primary_batch, secondary_batch)
            in  zip(grouper(primary_iter, self.primary_batch_size),
                    grouper(secondary_iter, self.secondary_batch_size))
        )

    def __len__(self):
        return len(self.primary_indices) // self.primary_batch_size
```

### Error messages and logs

Traceback (most recent call last):
  File "/data/gaoshenghan/exp_lite/train.py", line 21, in train
    train(cfg)
  File "/data/gaoshenghan/exp_lite/src/train.py", line 17, in train
    trainer.fit(task, datamodule=dataset)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 207, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1862, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 300, in _prepare_dataloader
    dataloader = _update_dataloader(dataloader, sampler, mode=mode)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 176, in _update_dataloader
    dl_kwargs = _get_dataloader_init_kwargs(dataloader, sampler, mode=mode)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 230, in _get_dataloader_init_kwargs
    dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode=mode))
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 288, in _dataloader_init_kwargs_resolve_sampler
    batch_size=batch_sampler.batch_size,
AttributeError: 'TwoStreamBatchSampler' object has no attribute 'batch_size'

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>
pytorch-lightning                  1.6.5

### More info

When I add self.batch_size to the batch_sampler, I get the following error：
Traceback (most recent call last):
  File "/data/gaoshenghan/exp_lite/train.py", line 21, in train
    train(cfg)
  File "/data/gaoshenghan/exp_lite/src/train.py", line 17, in train
    trainer.fit(task, datamodule=dataset)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 207, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1862, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 300, in _prepare_dataloader
    dataloader = _update_dataloader(dataloader, sampler, mode=mode)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 176, in _update_dataloader
    dl_kwargs = _get_dataloader_init_kwargs(dataloader, sampler, mode=mode)
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 230, in _get_dataloader_init_kwargs
    dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode=mode))
  File "/opt/conda/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 286, in _dataloader_init_kwargs_resolve_sampler
    batch_sampler = type(batch_sampler)(
TypeError: __init__() got an unexpected keyword argument 'batch_size'

**Comment by Hanshenggao** [comment]
When I set replace_sampler_ddp=False, the problem is solved, is there another way to solve it?

**Comment by awaelchli** [comment]
@Hanshenggao We recently updated the handling of these cases #18402. You are using an old version of Lightning, so I think upgrading is another option. If you can, please subclass BatchSampler class instead of Sampler, then Lightning can recognize that.

**Comment by Hanshenggao** [comment]
@awaelchli Thank you，i will try to subclass BatchSampler class instead of Sampler.If there are still errors, I will upgrade Lightning.Thank you so much

**Comment by awaelchli** [comment]
Did it work?

**Comment by Hanshenggao** [comment]
@awaelchli I try to subclass batchsampler class, but it can not work.So, i‘m trying to handle the distributed sampling.If it still doesn't work, I'll upgrade pytorch lightning.Many thanks for your attention!

**Comment by Hanshenggao** [comment]
@awaelchli When I tried to create distributed batchsampler, it can work!Thank you for your answer!Your answer helped me a lot！

**Comment by awaelchli** [comment]
@Hanshenggao Great you got it to work. Does that mean we should close the issue, or is there something left to action? The error message regarding this should already be improved in Lightning >= 2.1+, and users need to add distributed support in custom samplers anyway.
