### ISSUE TITLE
Logging failed when using mlflow with sqlite tracking uri

### ISSUE THREAD

**Issue by zmyjoe** [Lightning-AI/pytorch-lightning#19441]
### Bug description

I'm using Lightning with MLFlow. I want to use a local database to store tracked metadata, so I set the `tracking_uri` param in `MLFlowLogger` to `sqlite:////some_absolute_path/mlruns.db`. But I got `AssertionError` which says log_dir is none. Note that I'm controlling configs through lightning-cli.

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```yaml
trainer:
  logger:
    class_path: MLFlowLogger
    init_args:
      experiment_name: test
      tracking_uri: sqlite:////some_absolute_path/mlruns.db
      log_model: true
```

```python
cli = LightningCLI(run=False)
```

### Error messages and logs

Traceback (most recent call last):
  File "/home/user/code/main.py", line 15, in <module>
    cli_main()
  File "/home/user/code/main.py", line 9, in cli_main
    cli.trainer.fit(model=cli.model, datamodule=cli.datamodule)
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 948, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 93, in _call_setup_hook
    _call_callback_hooks(trainer, "setup", stage=fn)
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 247, in setup
    assert log_dir is not None
AssertionError

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.2.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 1.13.1
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.6
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
#- MLFlow version: 2.10.2
```

</details>

**Comment by zmyjoe** [comment]
Update: Using file as tracking uri (file:/home/user/mlruns) is also not working. It raises:

```
RuntimeError: SaveConfigCallback expected /home/user/mlruns/config.yaml to NOT exist. Aborting to avoid overwriting results of a previous run. You can delete the previous config file, set `LightningCLI(save_config_callback=None)` to disable config saving, or set `LightningCLI(save_config_kwargs={"overwrite": True})` to overwrite the config file.
```

**Comment by awaelchli** [comment]
@zmyjoe This is a duplicate of an existing issue: #16310 
You will find an explanation there.

**Comment by zmyjoe** [comment]
> @zmyjoe This is a duplicate of an existing issue: #16310 You will find an explanation there.

Thanks! I've got it.
