### ISSUE TITLE
Flag `use_distributed_sampler` is not work 

### ISSUE THREAD

**Issue by HuangChiEn** [Lightning-AI/pytorch-lightning#19665]
### Bug description

According to the document https://lightning.ai/docs/pytorch/stable/data/alternatives.html#limitations
If we want to customize sampler for 3rd lib, we should setup `use_distributed_sampler=False`. However, when I set this flag in `pl.Trainer(..., use_distributed_sampler=False)`, it still raised the error : "ValueError: DataLoader with IterableDataset: expected unspecified sampler option, but got sampler=<torch.utils.data.distributed.DistributedSampler object".

( By the way, the default sampler **CAN NOT**  let each GPU sees a different part of the dataset. The document also doesn't support well for webdataset. 
 

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug
I would say, pick up a example from webdataset and feed the `torch.utils.data.DistributedSampler(self.laion_train)` sampler in `wds.WebLoader(..., sampler=torch.utils.data.DistributedSampler(self.laion_train))`.

Key code snippet :
```
## 1. make webdataset
def wrap_wds(shard_path, ratio):
            warp_im_trfs = lambda tup : (self.img_transforms(tup[0]), tup[1]) 
            warp_txt_trfs = lambda tup : (tup[0], self.txt_transforms(tup[1]))
            
            # resampled=True : https://github.com/webdataset/webdataset/issues/225#issuecomment-1411143287
            pair_ds = wds.WebDataset(str(shard_path), resampled=True).decode('pilrgb', handler=wds.warn_and_continue).to_tuple("jpg", "txt", handler=wds.warn_and_continue)
            if self.img_transforms:
                pair_ds = pair_ds.map(warp_im_trfs, handler=wds.warn_and_continue)
            if self.txt_transforms:
                pair_ds = pair_ds.map(warp_txt_trfs, handler=wds.warn_and_continue)
            
            # split into batch 
            #pair_ds = pair_ds.batched(self.batch_size, partial=False)

            # You can also display the progress bar correctly by using both .with_epoch(epoch_length).with_length(epoch_length)
            # train/valid/test dataset have different ratio..
            total_num_ds = self.total_num_ds * ratio
            n_step = (total_num_ds // self.batch_size) 
            print(f"n_step : {n_step} per epoch!!")
            
            return pair_ds.with_epoch( int(n_step) ).with_length( int(n_step) )

self.laion_train = wrap_wds(self.tra_shard_path, self.split_ratio[0])

## 2. wrap sampler into webdataloader
loader = wds.WebLoader(
            self.laion_train, 
            batch_size=None, 
            shuffle=False,   # laion ds doesn't have order between samples, so we don't need to shuffle 
            pin_memory=True, 
            num_workers=self.num_workers,
            prefetch_factor=2,
            sampler=torch.utils.data.DistributedSampler(self.laion_train)
        )
        return loader.batched(self.batch_size)

## 3. trigger the bug
# above code snippet reveal the def train_dataloader(self): 
trainer = Trainer(**tra_cfg, use_distributed_sampler=False)  # 'sync_batchnorm=True', is necessary in multi-gpu, 
trainer.fit(train_loop, data_module)
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/data/joseph/IGNF/train.py", line 60, in <module>
    main(cfger)
  File "/data/joseph/IGNF/train.py", line 47, in main
    trainer.fit(train_loop, data_module)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 110, in run
    self.setup_data()
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 166, in setup_data
    dataloaders = _request_dataloader(source)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 309, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/data/joseph/IGNF/dataset.py", line 145, in val_dataloader
    loader = wds.WebLoader(
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/webdataset/compat.py", line 185, in __init__
    super().__init__(DataLoader(*args, **kw))
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/lightning_fabric/utilities/data.py", line 324, in wrapper
    init(obj, *args, **kwargs)
  File "/anaconda/envs/ignf/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 313, in __init__
    raise ValueError(
ValueError: DataLoader with IterableDataset: expected unspecified sampler option, but got sampler=<torch.utils.data.distributed.DistributedSampler object at 0x7feae41e13d0>
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
@HuangChiEn This is expected. The PyTorch DataLoader does not accept a sampler when the dataset is IterableDataset:
https://pytorch.org/docs/stable/data.html#data-loading-order-and-sampler

The error you got is from the PyTorch DataLoader, not Lightning. I suggest you look at the docs for WebDataset on how to configure it for distributed training: https://webdataset.github.io/webdataset/multinode/
(this is not controlled by Lightning)

**Comment by HuangChiEn** [comment]
> @HuangChiEn This is expected. The PyTorch DataLoader does not accept a sampler when the dataset is IterableDataset: https://pytorch.org/docs/stable/data.html#data-loading-order-and-sampler
> 
> The error you got is from the PyTorch DataLoader, not Lightning. I suggest you look at the docs for WebDataset on how to configure it for distributed training: https://webdataset.github.io/webdataset/multinode/ (this is not controlled by Lightning)

Thanks for your fast reply. 
Actually,  I have take a look about webdataset document. I also do agree your suggestion. However, the [document](https://lightning.ai/docs/pytorch/stable/data/alternatives.html#limitations) seems provide a way to handle the dataloader in **distributed way automatically**.  
> In a distributed multi-GPU setting (ddp), Lightning wraps the DataLoader’s sampler with a wrapper for distributed support. This makes sure that each GPU sees a different part of the dataset.

And, it also described: "As sampling can be implemented in arbitrary ways with custom iterables, Lightning might not be able to do this for you.". But i just want the default behavior (each gpu get a random subset of dataset, and `n_step = total_data // (batch_size * n_gpu)`). 

I though the default behavior should be able to adjust the `n_step` with awaring the num of gpu we used. Also note that the num of gpu setups in torchlightning, instead of torch or 3rd lib, it may be impossible to let the other library to deal with multi-gpu setting while `strategy=ddp` is executed in torchlightning trainer loop.
