### ISSUE TITLE
Pydantic AttributeError when using LightningDataModule

### ISSUE THREAD

**Issue by asusdisciple** [Lightning-AI/pytorch-lightning#19737]
### Bug description

I tried to create a LightningDataSet and wanted to do a type_check with pydantic for all input parameters, so I created a `Settings(BaseModel)` class with pydantic where DATA_DIR is just a regular string. However this results in an attribute error:

```
Traceback (most recent call last):
  File "/.../projects/classifier_lightning/main.py", line 16, in <module>
    mydata = LightningDataSet(data_dir=Settings.DATA_DIR,
  File "/.../projects/classifier_lightning/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 221, in __getattr__
    raise AttributeError(item)
AttributeError: DATA_DIR
```

I tried a pydantic 1.7.4 and 2.6 with similiar results.

### What version are you seeing the problem on?

v2.2

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by SkafteNicki** [comment]
The problem here is that you trying to access `DATA_DIR` as a class attribute rather than an instance attribute. In pydantic:
* Pydantic v1: You could sometimes access fields as class attributes
* Pydantic v2: Fields are only accessible on instances of the model, not the class itself

What you are doing is
```python
mydata = LightningDataSet(data_dir=Settings.DATA_DIR)
```
instead it should be
```python
settings = Settings()  # Create an instance
mydata = LightningDataSet(data_dir=settings.DATA_DIR)
```
this is not really a lightning issue.
Closing the issue, but please feel free to ping and reopen if necessary.
