### ISSUE TITLE
Add dog has an error: FileNotFoundError:

### ISSUE THREAD

**Issue by BaiYuanxi-dev** [Lightning-AI/pytorch-lightning#19862]
### Bug description

```
Traceback (most recent call last):
  File "D:\codes2\GaussianEditor\launch.py", line 252, in <module>
    main(args, extras)
  File "D:\codes2\GaussianEditor\launch.py", line 195, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "D:\softwares\anaconda3\envs\gsEditor\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "D:\softwares\anaconda3\envs\gsEditor\lib\site-packages\pytorch_lightning\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\softwares\anaconda3\envs\gsEditor\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\softwares\anaconda3\envs\gsEditor\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 969, in _run
    call._call_lightning_module_hook(self, "on_fit_start")
  File "D:\softwares\anaconda3\envs\gsEditor\lib\site-packages\pytorch_lightning\trainer\call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "D:\softwares\anaconda3\envs\gsEditor\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\codes2\GaussianEditor\threestudio\systems\GassuianEditorAdd.py", line 121, in on_fit_start
    p1 = subprocess.Popen(
  File "D:\softwares\anaconda3\envs\gsEditor\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\softwares\anaconda3\envs\gsEditor\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

```
we had an error : FileNotFoundError: [WinError 2] 系统找不到指定的文件。But it doesn't show which file .
Can you please take a look?

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by carmocca** [comment]
Your issue happens in code that doesn't come from Lightning:

```python
  File "D:\codes2\GaussianEditor\threestudio\systems\GassuianEditorAdd.py", line 121, in on_fit_start
```

There you will find the `on_fit_start` hook defined. This is what is running a subprocess call.

You can try debugging that.
