### ISSUE TITLE
AttributeError: module 'pytorch_lightning.callbacks' has no attribute 'ProgressBarBase'. Did you mean: 'ProgressBar'?

### ISSUE THREAD

**Issue by carusyte** [Lightning-AI/pytorch-lightning#19873]
### Bug description

I'm trying to add a custom progress bar (basically the intention is to suppress progress bar display completely), but the following error is thrown:
```
2024-05-16 10:02:14 - [worker tcp://127.0.0.1:40955] - marten.data.etl - ERROR - module 'pytorch_lightning.callbacks' has no attribute 'ProgressBarBase'
Traceback (most recent call last):
  File "/home/jx/git/marten/src/marten/models/worker_func.py", line 381, in log_metrics_for_hyper_params
    _, metrics = train(
                 ^^^^^^
  File "/home/jx/git/marten/src/marten/models/worker_func.py", line 298, in train
    for attempt in Retrying(
  File "/home/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/jx/.pyenv/versions/3.12.2/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jx/.pyenv/versions/3.12.2/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/jx/git/marten/src/marten/models/worker_func.py", line 305, in train
    m, metrics = _try_fitting(df,
                 ^^^^^^^^^^^^^^^^
  File "/home/jx/git/marten/src/marten/models/worker_func.py", line 252, in _try_fitting
    metrics = m.fit(
              ^^^^^^
  File "/home/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/neuralprophet/forecaster.py", line 1085, in fit
    metrics_df = self._train(
                 ^^^^^^^^^^^^
  File "/home/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/neuralprophet/forecaster.py", line 2757, in _train
    self.trainer, checkpoint_callback = utils.configure_trainer(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/neuralprophet/utils.py", line 961, in configure_trainer
    and any(isinstance(callback, pl.callbacks.ProgressBarBase) for callback in config["callbacks"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jx/.pyenv/versions/3.12.2/envs/venv_3.12.2/lib/python3.12/site-packages/neuralprophet/utils.py", line 961, in <genexpr>
    and any(isinstance(callback, pl.callbacks.ProgressBarBase) for callback in config["callbacks"])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pytorch_lightning.callbacks' has no attribute 'ProgressBarBase'. Did you mean: 'ProgressBar'?
```

### What version are you seeing the problem on?

v2.2

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
@carusyte From Lightning 1.9 to 2.0, this base class changed the name. It's just called `ProgressBar` now.
