### ISSUE TITLE
Loading saved config file fails because of InterpolationMode

### ISSUE THREAD

**Issue by iulialexandra** [Lightning-AI/pytorch-lightning#19965]
### Bug description

In the `SaveConfigCallback`, the config file that was used to run the current experiment is saved to `config.yaml` with this command: 

```
self.parser.save(
    self.config, config_path, skip_none=False, overwrite=self.overwrite, multifile=self.multifile
)
```

If I try to reproduce the experiment using the config file that pytorch lightning saved, the loading of the config file fails because `interpolation`, an argument to a few torchvision transforms, such as torchvision.transforms.Resize.
 is not correctly set.

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```python
Any config file that contains a transform such as 

- class_path: torchvision.transforms.Resize
     init_args:
         size: [768, 1024]

gets converted to this upon saving by pytorch lightning: 

 - class_path: torchvision.transforms.Resize
      init_args:
          size:
              - 768
              - 1024
          interpolation: bilinear
          max_size: null
          antialias: warn

Trying to load this converted config file fails.
```

### Error messages and logs

```
[19:44:29] ERROR            | Rank 0 | Exception occurred: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 364, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 364, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 231, in __getitem__
    sample = self.transform(sample)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 361, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 461, in resize
    raise TypeError(
TypeError: Argument interpolation should be a InterpolationMode or a corresponding Pillow integer constant

Traceback (most recent call last):
  File "/Users/iamiulialex/Documents/kaiko-eng/libs/ml_framework/kaiko/ml_framework/utils/log_redirect/decorator.py", line 54, in wrapper
    result = func(*args, **kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/libs/ml_framework/kaiko/ml_framework/__main__.py", line 108, in main
    return cli.CLI()
  File "/Users/iamiulialex/Documents/kaiko-eng/libs/ml_framework/kaiko/ml_framework/cli/cli.py", line 47, in __init__
    super().__init__(
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 364, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 364, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 231, in __getitem__
    sample = self.transform(sample)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 361, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/Users/iamiulialex/Documents/kaiko-eng/dist/export/python/virtualenvs/python-default/3.10.13/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 461, in resize
    raise TypeError(
TypeError: Argument interpolation should be a InterpolationMode or a corresponding Pillow integer constant
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:               None
        - available:         False
        - version:           None
* Lightning:
        - info-nce-pytorch:  0.1.4
        - lightning:         2.2.1
        - lightning-utilities: 0.11.2
        - pytorch-lightning: 2.2.5
        - torch:             2.1.1+cpu
        - torchdata:         0.7.1
        - torchmetrics:      1.4.0.post0
        - torchtext:         0.16.1+cpu
        - torchvision:       0.16.1+cpu
* Packages:
        - aadict:            0.2.3
        - absl-py:           2.1.0
        - accelerate:        0.30.1
        - adlfs:             2023.9.0
        - aenum:             3.1.15
        - affine:            2.4.0
        - agate:             1.9.1
        - aiobotocore:       2.5.4
        - aiofiles:          23.2.1
        - aiohttp:           3.9.5
        - aiohttp-cors:      0.7.0
        - aioitertools:      0.11.0
        - aiosignal:         1.3.1
        - albumentations:    1.3.1
        - alembic:           1.13.1
        - altair:            5.3.0
        - aniso8601:         9.0.1
        - antlr4-python3-runtime: 4.9.3
        - anyio:             4.4.0
        - asciitree:         0.3.3
        - asgiref:           3.8.1
        - asset:             0.6.13
        - asttokens:         2.4.1
        - async-timeout:     4.0.3
        - asyncpg:           0.29.0
        - attrs:             23.2.0
        - azure-ai-formrecognizer: 3.3.3
        - azure-common:      1.1.28
        - azure-core:        1.30.1
        - azure-data-tables: 12.5.0
        - azure-datalake-store: 0.0.53
        - azure-functions:   1.19.0
        - azure-identity:    1.16.0
        - azure-keyvault-secrets: 4.8.0
        - azure-storage-blob: 12.20.0
        - azure-storage-file-datalake: 12.15.0
        - azure-storage-queue: 12.10.0
        - babel:             2.15.0
        - backoff:           2.2.1
        - backports.tarfile: 1.2.0
        - bcrypt:            4.1.3
        - biopython:         1.83
        - bitsandbytes:      0.41.1
        - blinker:           1.8.2
        - blis:              0.7.11
        - boto3:             1.28.17
        - botocore:          1.31.17
        - braceexpand:       0.1.7
        - build:             1.2.1
        - cachetools:        5.3.3
        - catalogue:         2.0.10
        - certifi:           2024.6.2
        - cffi:              1.16.0
        - chardet:           5.2.0
        - charset-normalizer: 3.3.2
        - chispa:            0.9.4
        - chroma-hnswlib:    0.7.3
        - chromadb:          0.5.0
        - click:             8.1.7
        - click-plugins:     1.1.1
        - cligj:             0.7.2
        - cloudpathlib:      0.18.1
        - cloudpickle:       3.0.0
        - colorama:          0.4.6
        - coloredlogs:       14.0
        - colorful:          0.5.6
        - confection:        0.1.5
        - contourpy:         1.2.1
        - coverage:          7.5.3
        - croniter:          2.0.5
        - cryptography:      42.0.8
        - cycler:            0.12.1
        - cymem:             2.0.8
        - dacite:            1.8.1
        - daff:              1.3.46
        - dagster:           1.7.8
        - dagster-azure:     0.23.8
        - dagster-dbt:       0.23.8
        - dagster-deltalake: 0.23.8
        - dagster-graphql:   1.7.8
        - dagster-k8s:       0.23.8
        - dagster-pipes:     1.7.8
        - dagster-postgres:  0.23.8
        - dagster-prometheus: 0.23.8
        - dagster-shell:     0.23.8
        - dagster-slack:     0.23.8
        - dagster-webserver: 1.7.8
        - databricks-sdk:    0.17.0
        - databricks-sql-connector: 3.1.2
        - dataclasses:       0.6
        - dataproperty:      1.0.1
        - datasets:          2.19.2
        - dbt-adapters:      1.2.1
        - dbt-common:        1.3.0
        - dbt-core:          1.8.2
        - dbt-databricks:    1.8.1
        - dbt-extractor:     0.5.1
        - dbt-semantic-interfaces: 0.5.1
        - dbt-spark:         1.8.0
        - decorator:         5.1.1
        - deepdiff:          7.0.1
        - deepspeed:         0.12.6
        - defusedxml:        0.7.1
        - delta-spark:       3.2.0
        - deltalake:         0.17.4
        - deprecated:        1.2.14
        - dicomweb-client:   0.59.1
        - dill:              0.3.8
        - distlib:           0.3.8
        - distro:            1.9.0
        - dlup:              0.3.38
        - dm-tree:           0.1.8
        - dnspython:         2.6.1
        - docker:            7.1.0
        - docker-pycreds:    0.4.0
        - docstring-parser:  0.16
        - email-validator:   2.1.1
        - et-xmlfile:        1.1.0
        - evaluate:          0.4.2
        - exceptiongroup:    1.2.1
        - execnet:           2.1.1
        - executing:         2.0.1
        - farama-notifications: 0.0.4
        - fastapi:           0.111.0
        - fastapi-cli:       0.0.4
        - fasteners:         0.19
        - filelock:          3.14.0
        - fiona:             1.9.6
        - flask:             3.0.3
        - flatbuffers:       24.3.25
        - fonttools:         4.53.0
        - formenergy-observability: 0.3.2
        - frozenlist:        1.4.1
        - fsspec:            2023.9.2
        - geopandas:         0.14.4
        - ghp-import:        2.1.0
        - gitdb:             4.0.11
        - gitpython:         3.1.43
        - giturlparse:       0.12.0
        - globre:            0.1.5
        - google-api-core:   2.19.0
        - google-auth:       2.29.0
        - googleapis-common-protos: 1.63.1
        - gql:               3.5.0
        - graphene:          3.3
        - graphql-core:      3.2.3
        - graphql-relay:     3.2.0
        - greenlet:          3.0.3
        - griffe:            0.45.2
        - grpcio:            1.64.1
        - grpcio-health-checking: 1.62.2
        - gymnasium:         0.28.1
        - h11:               0.14.0
        - h2:                4.1.0
        - h5py:              3.11.0
        - highdicom:         0.22.0
        - hjson:             3.1.0
        - hpack:             4.0.0
        - httpcore:          1.0.5
        - httptools:         0.6.1
        - httpx:             0.27.0
        - huggingface-hub:   0.23.3
        - humanfriendly:     10.0
        - hydra-core:        1.3.2
        - hyperframe:        6.0.1
        - hypothesis:        6.54.6
        - idna:              3.7
        - imagecodecs:       2023.7.10
        - imageio:           2.34.1
        - importlib-metadata: 6.11.0
        - importlib-resources: 6.4.0
        - info-nce-pytorch:  0.1.4
        - iniconfig:         2.0.0
        - ipython:           8.25.0
        - isodate:           0.6.1
        - itsdangerous:      2.2.0
        - jaraco.classes:    3.4.0
        - jaraco.context:    5.3.0
        - jaraco.functools:  4.0.1
        - jax-jumpy:         1.0.0
        - jedi:              0.19.1
        - jinja2:            3.1.4
        - jmespath:          1.0.1
        - joblib:            1.4.2
        - jsonargparse:      4.28.0
        - jsonlines:         4.0.0
        - jsonschema:        4.22.0
        - jsonschema-specifications: 2023.12.1
        - jwt:               1.3.1
        - kaiko-cfmpb:       0.0.1
        - kaiko-conductor:   0.0.4
        - kaiko-dagster:     0.0.51
        - kaiko-data-io:     0.0.15
        - kaiko-data-loading: 0.0.36
        - kaiko-databits:    0.0.8
        - kaiko-fm-pipeline: 0.0.1
        - kaiko-fsspec-utils: 0.0.8
        - kaiko-geometry:    0.0.40
        - kaiko-image-annotation: 0.0.38
        - kaiko-image-augmentation: 0.0.27
        - kaiko-image-data:  0.0.49
        - kaiko-image-processing: 0.0.40
        - kaiko-incognito:   0.0.1
        - kaiko-inference-engine: 0.0.16
        - kaiko-inference-tools: 0.0.8
        - kaiko-ingestion:   0.0.24
        - kaiko-llm-dev-tool: 0.0.1
        - kaiko-llm-serve:   0.0.1
        - kaiko-llm-triage:  0.0.64
        - kaiko-lmm-bench:   0.0.11
        - kaiko-mirax:       0.0.10
        - kaiko-ml-framework: 0.0.251
        - kaiko-multiprocessing: 0.0.6
        - kaiko-nki-dbt:     0.0.24
        - kaiko-nlp:         1.0.84
        - kaiko-online-patching: 0.0.70
        - kaiko-ray-plugins: 0.0.1
        - kaiko-test-services: 1.0.20
        - kaiko-vef:         0.0.31
        - kaiko-wsi:         0.0.46
        - kerchunk:          0.2.5
        - keyring:           25.2.1
        - kiwisolver:        1.4.5
        - kornia:            0.7.2
        - kornia-rs:         0.1.3
        - kubernetes:        29.0.0
        - langcodes:         3.4.0
        - language-data:     1.2.0
        - lark:              1.1.9
        - lazy-loader:       0.4
        - leather:           0.4.0
        - lightly:           1.5.6
        - lightly-utils:     0.0.2
        - lightning:         2.2.1
        - lightning-utilities: 0.11.2
        - linkify-it-py:     2.0.3
        - llvmlite:          0.42.0
        - lm-eval:           0.4.2
        - logbook:           1.5.3
        - loguru:            0.7.2
        - lxml:              5.2.2
        - lz4:               4.3.3
        - mako:              1.3.5
        - marisa-trie:       1.2.0
        - markdown:          3.6
        - markdown-it-py:    3.0.0
        - markupsafe:        2.1.5
        - mashumaro:         3.13
        - matplotlib:        3.9.0
        - matplotlib-inline: 0.1.7
        - mbstrdecoder:      1.1.3
        - mdit-py-plugins:   0.4.1
        - mdurl:             0.1.2
        - memray:            1.12.0
        - mergedeep:         1.3.4
        - minimal-snowplow-tracker: 0.0.2
        - mkdocs:            1.6.0
        - mkdocs-autorefs:   1.0.1
        - mkdocs-gen-files:  0.5.0
        - mkdocs-get-deps:   0.2.0
        - mkdocs-literate-nav: 0.6.1
        - mkdocs-material:   9.5.26
        - mkdocs-material-extensions: 1.3.1
        - mkdocstrings:      0.25.1
        - mkdocstrings-python: 1.10.3
        - mmh3:              4.1.0
        - monai:             1.3.1
        - monai-deploy-app-sdk: 0.5.0
        - monotonic:         1.6
        - more-itertools:    10.2.0
        - mpmath:            1.3.0
        - msal:              1.28.0
        - msal-extensions:   1.1.0
        - msgpack:           1.0.8
        - msrest:            0.7.1
        - multidict:         6.0.5
        - multiprocess:      0.70.16
        - murmurhash:        1.0.10
        - networkx:          3.2.1
        - nibabel:           4.0.2
        - ninja:             1.11.1.1
        - nltk:              3.8.1
        - numba:             0.59.1
        - numcodecs:         0.12.1
        - numexpr:           2.10.0
        - numpy:             1.23.5
        - oauthlib:          3.2.2
        - omegaconf:         2.3.0
        - onnx:              1.16.1
        - onnxruntime:       1.15.1
        - openai:            1.31.1
        - opencensus:        0.11.4
        - opencensus-context: 0.1.3
        - opencensus-ext-azure: 1.1.13
        - opencv-python:     4.10.0.82
        - opencv-python-headless: 4.10.0.82
        - openpyxl:          3.1.3
        - openslide-python:  1.3.1
        - opentelemetry-api: 1.25.0
        - opentelemetry-exporter-otlp: 1.25.0
        - opentelemetry-exporter-otlp-proto-common: 1.25.0
        - opentelemetry-exporter-otlp-proto-grpc: 1.25.0
        - opentelemetry-exporter-otlp-proto-http: 1.25.0
        - opentelemetry-instrumentation: 0.46b0
        - opentelemetry-instrumentation-asgi: 0.46b0
        - opentelemetry-instrumentation-fastapi: 0.46b0
        - opentelemetry-instrumentation-requests: 0.46b0
        - opentelemetry-instrumentation-sqlalchemy: 0.46b0
        - opentelemetry-proto: 1.25.0
        - opentelemetry-sdk: 1.25.0
        - opentelemetry-semantic-conventions: 0.46b0
        - opentelemetry-util-http: 0.46b0
        - ordered-set:       4.1.0
        - orjson:            3.10.3
        - overrides:         7.7.0
        - packaging:         21.3
        - paginate:          0.5.6
        - pandas:            2.1.4
        - paramiko:          3.4.0
        - parsedatetime:     2.6
        - parso:             0.8.4
        - pathspec:          0.12.1
        - pathvalidate:      3.2.0
        - pdf2image:         1.17.0
        - peft:              0.7.0
        - pendulum:          3.0.0
        - pex:               2.3.2
        - pexpect:           4.9.0
        - phonenumbers:      8.13.38
        - pillow:            10.3.0
        - pillow-jpls:       1.3.2
        - pip:               23.0.1
        - pkgconfig:         1.5.5
        - platformdirs:      4.2.2
        - playwright:        1.44.0
        - plotly:            5.22.0
        - pluggy:            1.5.0
        - portalocker:       2.8.2
        - posthog:           3.5.0
        - preshed:           3.0.9
        - presidio-analyzer: 2.2.354
        - presidio-image-redactor: 0.0.52
        - prometheus-client: 0.20.0
        - prompt-toolkit:    3.0.46
        - proto-plus:        1.23.0
        - protobuf:          4.25.3
        - psutil:            5.9.8
        - psycopg2-binary:   2.9.9
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py:                1.11.0
        - py-cpuinfo:        9.0.0
        - py-spy:            0.3.14
        - py4j:              0.10.9.7
        - pyaml:             23.9.7
        - pyarrow:           14.0.2
        - pyarrow-hotfix:    0.6
        - pyasn1:            0.6.0
        - pyasn1-modules:    0.4.0
        - pybind11:          2.12.0
        - pycocotools:       2.0.7
        - pycparser:         2.22
        - pydantic:          1.10.15
        - pydeck:            0.9.1
        - pydicom:           2.4.4
        - pyee:              11.1.0
        - pyfaidx:           0.8.1.1
        - pygments:          2.18.0
        - pyjwt:             2.8.0
        - pymdown-extensions: 10.8.1
        - pymonad:           2.4.0
        - pynacl:            1.5.0
        - pynvml:            11.5.0
        - pyopenssl:         24.1.0
        - pyparsing:         3.1.2
        - pypdf2:            3.0.1
        - pypika:            0.48.9
        - pypng:             0.20220715.0
        - pyproj:            3.6.1
        - pyproject-hooks:   1.1.0
        - pysankeybeta:      1.4.0
        - pyspark:           3.5.0
        - pytablewriter:     1.2.0
        - pytesseract:       0.3.10
        - pytest:            7.4.4
        - pytest-asyncio:    0.23.7
        - pytest-check:      2.3.1
        - pytest-cov:        4.1.0
        - pytest-forked:     1.6.0
        - pytest-lazy-fixture: 0.6.3
        - pytest-mock:       3.14.0
        - pytest-repeat:     0.9.3
        - pytest-rerunfailures: 14.0
        - pytest-timeout:    2.3.1
        - pytest-xdist:      2.5.0
        - python-dateutil:   2.9.0.post0
        - python-dotenv:     1.0.1
        - python-multipart:  0.0.9
        - python-slugify:    8.0.4
        - pytimeparse:       1.1.8
        - pytorch-lightning: 2.2.5
        - pytz:              2024.1
        - pyvips:            2.2.3
        - pyyaml:            6.0.1
        - pyyaml-env-tag:    0.1
        - qudida:            0.0.4
        - rapidfuzz:         3.9.3
        - rasterio:          1.3.10
        - ray:               2.11.0
        - ray-cpp:           2.11.0
        - ray-pex-env:       0.0.11
        - referencing:       0.35.1
        - regex:             2024.5.15
        - requests:          2.32.3
        - requests-file:     2.1.0
        - requests-mock:     1.12.1
        - requests-oauthlib: 2.0.0
        - requests-toolbelt: 1.0.0
        - retrying:          1.3.4
        - rich:              13.7.1
        - rouge-metric:      1.0.1
        - rouge-score:       0.1.2
        - rpds-py:           0.18.1
        - rsa:               4.9
        - rt-utils:          1.2.7
        - ruamel.yaml:       0.18.6
        - ruamel.yaml.clib:  0.2.8
        - s3fs:              2023.9.2
        - s3transfer:        0.6.2
        - sacrebleu:         2.4.2
        - safetensors:       0.4.3
        - scikit-image:      0.23.2
        - scikit-learn:      1.3.2
        - scipy:             1.13.1
        - seaborn:           0.13.2
        - segment-anything:  1.0
        - sentry-sdk:        2.5.0
        - setproctitle:      1.3.3
        - setuptools:        69.5.1
        - shapely:           2.0.4
        - shellingham:       1.5.4
        - shtab:             1.7.1
        - simpleitk:         2.3.1
        - six:               1.16.0
        - skorch:            1.0.0
        - slack-sdk:         3.27.2
        - smart-open:        7.0.4
        - smmap:             5.0.1
        - sniffio:           1.3.1
        - snuggs:            1.4.7
        - sortedcontainers:  2.4.0
        - spacy:             3.7.5
        - spacy-legacy:      3.0.12
        - spacy-loggers:     1.0.5
        - speechrecognition: 3.10.4
        - sqlalchemy:        2.0.30
        - sqlglot:           25.0.2
        - sqlglotrs:         0.2.5
        - sqlitedict:        2.1.0
        - sqlparams:         6.0.1
        - sqlparse:          0.5.0
        - srsly:             2.4.8
        - sshtunnel:         0.4.0
        - st-copy-to-clipboard: 0.1.6
        - st-pages:          0.4.5
        - stack-data:        0.6.3
        - starlette:         0.37.2
        - streamlit:         1.35.0
        - streamlit-chat:    0.1.1
        - striprtf:          0.0.26
        - structlog:         23.3.0
        - sympy:             1.12.1
        - tabledata:         1.3.3
        - tabulate:          0.9.0
        - tcolorpy:          0.1.6
        - tenacity:          8.3.0
        - tensorboard:       2.16.2
        - tensorboard-data-server: 0.7.2
        - tensorboardx:      2.6.2.2
        - text-unidecode:    1.3
        - textual:           0.65.1
        - thinc:             8.2.4
        - threadpoolctl:     3.5.0
        - thrift:            0.16.0
        - tifffile:          2024.5.22
        - tiffslide:         2.4.0
        - tifftools:         1.5.2
        - tiktoken:          0.7.0
        - time-machine:      2.14.1
        - timm:              0.9.16
        - tldextract:        5.1.2
        - tokenizers:        0.19.1
        - toml:              0.10.2
        - tomli:             2.0.1
        - toolz:             0.12.1
        - toposort:          1.10
        - torch:             2.1.1+cpu
        - torchdata:         0.7.1
        - torchmetrics:      1.4.0.post0
        - torchtext:         0.16.1+cpu
        - torchvision:       0.16.1+cpu
        - tornado:           6.4
        - tqdm:              4.66.4
        - tqdm-multiprocess: 0.0.11
        - traitlets:         5.14.3
        - transformers:      4.41.2
        - trl:               0.9.3
        - typedspark:        1.4.3
        - typeguard:         4.3.0
        - typepy:            1.3.2
        - typer:             0.12.3
        - typeshed-client:   2.5.1
        - typing-extensions: 4.12.1
        - tyro:              0.8.4
        - tzdata:            2024.1
        - uc-micro-py:       1.0.3
        - ujson:             5.10.0
        - universal-pathlib: 0.2.2
        - urllib3:           1.26.18
        - uvicorn:           0.30.1
        - uvloop:            0.19.0
        - validators:        0.20.0
        - virtualenv:        20.26.2
        - wandb:             0.17.0
        - wasabi:            1.1.3
        - watchdog:          4.0.1
        - watchfiles:        0.22.0
        - wcwidth:           0.2.13
        - weasel:            0.4.1
        - webdataset:        0.2.86
        - websocket-client:  1.8.0
        - websockets:        12.0
        - werkzeug:          3.0.3
        - word2number:       1.1
        - wrapt:             1.16.0
        - xformers:          0.0.23
        - xlsxwriter:        3.2.0
        - xmltodict:         0.13.0
        - xxhash:            3.4.1
        - yarl:              1.9.4
        - zarr:              2.18.2
        - zipp:              3.19.2
        - zstandard:         0.22.0
* System:
        - OS:                Darwin
        - architecture:
                - 64bit
                - 
        - processor:         arm
        - python:            3.10.13
        - release:           23.5.0
        - version:           Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000

</details>

**Comment by iulialexandra** [comment]
It seems the issue was fixed with torchvision.transforms.v2
