### ISSUE TITLE
_atomic_save with transaction cause "Invalid cross-device link" error

### ISSUE THREAD

**Issue by RichardChe** [Lightning-AI/pytorch-lightning#20270]
### Bug description

I Upgraded my pl verison from 2.0.4 to 2.4. The same training code will have the error below
```
2024-09-06 23:01:53 [on_validation_epoch_end] collecting matched instance from 64 ranks
2024-09-06 23:02:17 [on_validation_epoch_end] end
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp7ue72_bg' -> '/xxx/model/ckpt-epoch=000.ckpt'
```
When I check the corresponding code difference, I find the difference below
``` diff
@@ -65,8 +78,69 @@ def _atomic_save(checkpoint: Dict[str, Any], filepath: Union[str, Path]) -> None
             accepts.
         filepath: The path to which the checkpoint will be saved.
             This points to the file that the checkpoint will be stored in.
+
     """
     bytesbuffer = io.BytesIO()
+    log.debug(f"Saving checkpoint: {filepath}")
     torch.save(checkpoint, bytesbuffer)
-    with fsspec.open(filepath, "wb") as f:
+
+    # We use a transaction here to avoid file corruption if the save gets interrupted
+    fs, urlpath = fsspec.core.url_to_fs(str(filepath))
+    with fs.transaction, fs.open(urlpath, "wb") as f:
         f.write(bytesbuffer.getvalue())
```
**It seems that the using of transaction will cause the error when moving a file between different filesystem. Is there any solution?** 

### What version are you seeing the problem on?

v2.4

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.4.0):
#- PyTorch Version (e.g., 2.4):
#- Python version (e.g., 3.12):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

**Comment by antonzub99** [comment]
Same thing happening to me on 2.4.0 version, but it works fine on 2.3.1

**Comment by RichardChe** [comment]
> Same thing happening to me on 2.4.0 version, but it works fine on 2.3.1

Yes, same situation..

**Comment by stan13** [comment]
Same thing happening for me on version 2.4, but only occasionally, curious why we see this only sometimes?

**Comment by haru-256** [comment]
Same thing happening for me on version 2.5.0.post0.
I wantted to save model checkpoints into disk mounted by [Cloud Storage FUSE](https://cloud.google.com/storage/docs/gcs-fuse?hl=en), but "Invalid cross-device link" error is occured.

**Comment by dhinz94** [comment]
Same, when saving a checkpoint to a network drive.
The last working version is 2.3.3.

https://github.com/Lightning-AI/pytorch-lightning/blame/cf348673eda662cc2e9aa71a72a19b8774f85718/src/lightning/fabric/utilities/cloud_io.py#L65-L80

**Comment by siemdejong** [comment]
Same with 2.5.1. During the handling of the exception above, another exception occurs.

<details>

<summary>PermissionError: [Errno 1] Operation not permitted</summary>

```python
Traceback (most recent call last):
  File "/run.py", line 116, in <module>
    trainer.fit(model, data)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1012, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 217, in run
    self.on_advance_end()
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 470, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 227, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 325, in on_train_epoch_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 385, in _save_topk_checkpoint
    self._save_monitor_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 705, in _save_monitor_checkpoint
    self._update_best_and_save(current, trainer, monitor_candidates)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 757, in _update_best_and_save
    self._save_checkpoint(trainer, filepath)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 390, in _save_checkpoint
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1397, in save_checkpoint
    self.strategy.save_checkpoint(checkpoint, filepath, storage_options=storage_options)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 491, in save_checkpoint
    self.checkpoint_io.save_checkpoint(checkpoint, filepath, storage_options=storage_options)
  File "/opt/conda/lib/python3.11/site-packages/lightning/fabric/plugins/io/torch_io.py", line 58, in save_checkpoint
    _atomic_save(checkpoint, path)
  File "/opt/conda/lib/python3.11/site-packages/lightning/fabric/utilities/cloud_io.py", line 89, in _atomic_save
    with fs.transaction, fs.open(urlpath, "wb") as f:
  File "/opt/conda/lib/python3.11/site-packages/fsspec/transaction.py", line 28, in __exit__
    self.complete(commit=exc_type is None)
  File "/opt/conda/lib/python3.11/site-packages/fsspec/transaction.py", line 42, in complete
    f.commit()
  File "/opt/conda/lib/python3.11/site-packages/fsspec/implementations/local.py", line 356, in commit
    shutil.move(self.temp, self.path)
  File "/opt/conda/lib/python3.11/shutil.py", line 873, in move
    copy_function(src, real_dst)
  File "/opt/conda/lib/python3.11/shutil.py", line 449, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.11/shutil.py", line 380, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
PermissionError: [Errno 1] Operation not permitted
```

</details>

**Comment by siemdejong** [comment]
Are you open to a PR?

Would it make sense to do the following?
- `try ... except ...` and catch the permission error and fallback in case of this permission error.
- Always doing the fallback might possibly be a breaking change, but changing `TorchCheckpointIO.save_checkpoint`'s `storage_options` to include a `non_atomic_fallback` key that can be used by a new `class NoAtomicCheckpointIO(TorchCheckpointIO)` allows users to choose the fallback for themselves.
- Users can be pointed to resorting to another checkpointing class via the permission error, something like "You're trying to write to another filesystem that doesn't support atomic writes. Please use `Trainer(plugins=[NoAtomicCheckpointIO()])` to save checkpoints there at the cost of surely valid checkpoints."

**Comment by siemdejong** [comment]
I see there are discussions adressing this issue here https://github.com/Lightning-AI/pytorch-lightning/pull/20011 here https://github.com/fsspec/filesystem_spec/issues/1797. Looks like an issue with `fsspec` itself. @brandon-smith-xperi, do you have an update?

**Comment by anticausal** [comment]
@siemdejong I haven't had a chance to dive into the problem deeply, but I think you have probably addressed the underlying issue here (https://github.com/fsspec/filesystem_spec/issues/1797), thanks!

**Comment by brandon-smith-xperi** [comment]
@siemdejong I haven't had a chance to dive into the problem deeply, but I think you have probably addressed the underlying issue here (https://github.com/fsspec/filesystem_spec/issues/1797), thanks!

**Comment by siemdejong** [comment]
To be sure I think this issue could use a proper minimal failing test reproducing the issue, but I'm unsure how to write one. Could anyone help me with this? Or is a test not needed?

**Comment by siemdejong** [comment]
Fixing https://github.com/fsspec/filesystem_spec/issues/1797 didn't fix this issue.

<details>

<summary>traceback</summary>

train_vmf_loss=-1.55]Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/shutil.py", line 853, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp657zwu1c' -> '/path/to/checkpoint.ckpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/entrypoint.py", line 134, in <module>
    trainer.fit(model, data)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1012, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 217, in run
    self.on_advance_end()
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 470, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 227, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 325, in on_train_epoch_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 387, in _save_topk_checkpoint
    self._save_none_monitor_checkpoint(trainer, monitor_candidates)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 715, in _save_none_monitor_checkpoint
    self._save_checkpoint(trainer, filepath)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 390, in _save_checkpoint
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1397, in save_checkpoint
    self.strategy.save_checkpoint(checkpoint, filepath, storage_options=storage_options)
  File "/opt/conda/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 491, in save_checkpoint
    self.checkpoint_io.save_checkpoint(checkpoint, filepath, storage_options=storage_options)
  File "/opt/conda/lib/python3.11/site-packages/lightning/fabric/plugins/io/torch_io.py", line 58, in save_checkpoint
    _atomic_save(checkpoint, path)
  File "/opt/conda/lib/python3.11/site-packages/lightning/fabric/utilities/cloud_io.py", line 89, in _atomic_save
    with fs.transaction, fs.open(urlpath, "wb") as f:
  File "/opt/conda/lib/python3.11/site-packages/fsspec/transaction.py", line 28, in __exit__
    self.complete(commit=exc_type is None)
  File "/opt/conda/lib/python3.11/site-packages/fsspec/transaction.py", line 44, in complete
    f.commit()
  File "/opt/conda/lib/python3.11/site-packages/fsspec/implementations/local.py", line 433, in commit
    shutil.move(self.temp, self.path)
  File "/opt/conda/lib/python3.11/shutil.py", line 873, in move
    copy_function(src, real_dst)
  File "/opt/conda/lib/python3.11/shutil.py", line 449, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.11/shutil.py", line 380, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
PermissionError: [Errno 1] Operation not permitted

</details>

**Comment by siemdejong** [comment]
For anyone still having this issue, could you please see if
```bash
pip install "fsspec[http] @ git+https://github.com/fsspec/filesystem_spec@372ef69d2995972add754720e43843f349275acf"
```
solves your issue? It solves the issue for the system I am using, but it would be good to verify on other systems if possible.
