### ISSUE TITLE
importing fails after matplotlib is installed

### ISSUE THREAD

**Issue by niphiwi** [Lightning-AI/pytorch-lightning#20478]
### Bug description

I receive ```ValueError: bad marshal data (unknown type code)``` when importing pytorch lightning ```import pytorch_lightning```. I could recreate this with a fresh environment with only pytorch, lightning, and matplotlib installed.

### What version are you seeing the problem on?

v2.4

### Error messages and logs

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/lightning/__init__.py", line 20, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/lightning/pytorch/__init__.py", line 27, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/lightning/pytorch/callbacks/__init__.py", line 14, in <module>
    from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 26, in <module>
    from lightning.pytorch.callbacks.callback import Callback
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/lightning/pytorch/callbacks/callback.py", line 22, in <module>
    from lightning.pytorch.utilities.types import STEP_OUTPUT
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/lightning/pytorch/utilities/types.py", line 42, in <module>
    from torchmetrics import Metric
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/__init__.py", line 37, in <module>
    from torchmetrics import functional  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/metric.py", line 42, in <module>
    from torchmetrics.utilities.plot import _AX_TYPE, _PLOT_OUT_TYPE, plot_single_or_multi_val
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/torchmetrics/utilities/plot.py", line 25, in <module>
    import matplotlib
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/<user>/miniforge3/envs/gnn/lib/python3.12/site-packages/matplotlib/colors.py", line 52, in <module>
    from PIL import Image
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1124, in get_code
  File "<frozen importlib._bootstrap_external>", line 753, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
```

### Environment

<details>
  <summary>Current environment</summary>

```
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - aom=3.3.0=h27087fc_1
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py312h68727a3_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.0=h59595ed_0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=4.4.1=h964e5f1_4
  - filelock=3.16.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.2=py312h178313f_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2024.10.0=pyhd8ed1ab_1
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py312h7201bc8_3
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=8.5.0=hfac3d4d_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.4=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py312h68727a3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=8_h3b12eaf_netlib
  - libclang-cpp18.1=18.1.8=default_hf981a13_5
  - libclang13=19.1.2=default_h9c6a7e4_1
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.7.77=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_0
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.80.2=hf974151_0
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - libllvm18=18.1.8=h8b73ec9_2
  - libllvm19=19.1.2=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopengl=1.7.0=ha4b6fd6_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.6=h035377e_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.7=h4c95cb1_3
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning=2.4.0=pyhd8ed1ab_0
  - lightning-utilities=0.11.9=pyhff2d567_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib=3.9.3=py312h7900ff3_0
  - matplotlib-base=3.9.3=py312hd3ec401_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - ncurses=6.5=he02047a_1
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.0=py312h7e784f5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - pcre2=10.43=hcad00b1_0
  - pillow=10.3.0=py312hdcec9eb_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pyside6=6.7.2=py312h91f0f75_4
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.12=5_cp312
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-lightning=2.4.0=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py312h66e93f0_1
  - qhull=2020.2=h434a139_5
  - qt6-main=6.7.2=h402ef58_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_1
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.17.0=pyhd8ed1ab_0
  - svt-av1=1.1.0=h27087fc_1
  - sympy=1.13.3=pypyh2585a3b_103
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.5.1=py312_cu124
  - torchmetrics=1.5.2=pyhe5570ce_0
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu124
  - tornado=6.4.2=py312h66e93f0_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py312h66e93f0_1
  - urllib3=2.2.3=pyhd8ed1ab_1
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-cursor=0.1.4=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
```

</details>

**Comment by niphiwi** [comment]
Seems like the issue had something to do with my conda environment.

**Comment by niphiwi** [comment]
Seems like the issue had something to do with my conda environment.
